ml-explore/mlx-examples

- .gitignore
- whisper/benchmark.py
While running a benchmark, if the user adds the `--all` flag,
```
python benchmark.py  --all
```
Then, all the models - `[tiny, base, small, medium, large]` will be benchmarked.
Also, updated `.gitignore` to ignore `.vscode/` and `.idea/`
> feat: benchmark all models (with `--all` flag)

- stable_diffusion/stable_diffusion/vae.py
This layer name is quant rather than query
> fix: typo in variable name

- mistral/mistral.py
Pass the batch size of token generation via argument `--tokens_per_eval`
```
python mistral.py --model_path model --prompt "hello" --temp 0 --max_tokens 256 --tokens_per_eval 1
```
> Mistral: Pass argument --tokens_per_eval for token generation

- llama/convert.py
If the model is large, for example, llama-2-13b, the convert.py will try to load the model with CUDA device and reports an error.
```shell
✘ python3 ./convert.py ../../llama/llama-2-13b/consolidated.00.pth llama-2-13b
File "/Users/starfish/working/llm/mlx-examples/llama/./convert.py", line 49, in <module>
state = torch.load(args.torch_weights)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 1014, in load
return _load(opened_zipfile,
^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 1422, in _load
result = unpickler.load()
^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 1392, in persistent_load …
```
> fix: fix issue #54, use CPU device to load the Torch model

- lora/README.md
this PR makes the docs on Llama model downloads consistent for lora and llama examples.
> fix "request access" form url for Llama models

- bert/README.md
It just adds the missing backslash.
> Fix convert.py instructions for Bert model

- bert/model.py
- bert/requirements.txt
Reduced duplication in the implementation. Tested on my machine (with a local mlx build) and gives the same results as before and as the HF implementation.
> Update BERT to take advantage of bias param in MultiHeadAttention

- whisper/README.md
Corrected spelling of proprietary terms in [whisper/README.md](https://github.com/ml-explore/mlx-examples/blob/main/whisper/README.md): 
- _whisper_ to **_Whisper_**,
- _Open AI_ to **_OpenAI_**, 
- _MacOS_ to **_macOS_**
> Typo fix in whisper/README

- cifar/README.md
- cifar/dataset.py
- cifar/main.py
- cifar/requirements.txt
- cifar/resnet.py
Added an implementation for training ResNets for CIFAR-10, as specified in the original [paper](https://arxiv.org/abs/1512.03385), as currently there aren't any CNN examples.
Since `mlx` currently doesn't have a native `BatchNorm` implementation, using `LayerNorm` instead, will add options for switching to `BatchNorm` in the future. 
Supports the following ResNet configurations: ResNet-20, ResNet-32, ResNet-44, ResNet-56, ResNet-110, ResNet-1202.
Also showcases using `mlx-data` for data loading/augmentation.
> Added CIFAR-10 + ResNet example

- phi2/requirements.txt
torch was not added as a dependency in phi-2 requirements.txt
> minor dependency fix in phi-2

- phi2/phi2.py
`seed` was not being passed to generate(). 
This quick fix will let folks experiment with `--temp/--seed`!
> phi-2: fix --temp/--seed arguments.

- llama/llama.py
pass few shot file name to --few-shot to avoid interpreting --prompt once a string and once as filename.
relates to #139
> pass few shot file name to --few-shot 

- ACKNOWLEDGMENTS.md
- t5/convert.py
- t5/t5.py
I didn't manage to make it work with float16, but from my tests it works ok with bfloat16. There are some small discrepancies in the generated text, but I think it will usually be worth the speed-up.
Also:
- Adds myself to acknowledgments :)
- Adds param to serialize to float32 (I even considered making it the default. Serializing to float16 can result in some differences, even when running in float32).
- Sets default `n_positions` to 512, which is not set in some models, such as the t5 v1.1 series.
> T5: Change default dtype to bfloat16

- phi2/phi2.py
This is for symmetry with the rest of the example scripts, and to avoid workarounds like this one because of the hardcoded path: https://huggingface.co/mlx-community/phi-2/blob/674d36e7f00751d12543893cd62e2f6c733016d6/README.md?code=true#L33
> Add `--model_path` to phi-2 example script

- mistral/convert.py
- mistral/mistral.py
This would go with PRs like this one to the model repos: https://huggingface.co/mlx-community/mistral-7B-v0.1/discussions/7
The advantages of standardizing on `config.json` instead of `params.json`, and adding a `model_type` field, would be:
- Better compatibility with repos in the Hugging Face Hub, easier retrieval of stats.
- Easy (hopefully) support of existing safetensors repos when https://github.com/ml-explore/mlx/pull/215 is ready. IIUC, Mistral safetensors files should work out of the box.
- Easier election of inference code down the line, based on `model_type`.
> Use config.json, add model_type

- llms/phi2/README.md
This PR fixes a minor typo in the instruction to run `phi2.py`. The argument is `--max-tokens` not `--max_tokens`.
> fix typo in readme

- llms/phi2/phi2.py
Since the reorg in #145, the paths to the load the model weights need to be updated. This PR updates the path to load the weights for `phi2`.
cc @awni
> update path to load weights

- t5/hf_t5.py
- t5/t5.py
The t5 example doesn't support the ByT5 series ([paper](https://arxiv.org/abs/2105.13626)) because it uses more layers in the decoder than in the encoder. Also, for some reason, we have to use `AutoTokenizer` instead of the `T5Tokenizer`.
The model is not fine-tuned, so the output is garbage, but I checked it matches HF's.
```sh
$ export MODEL="google/byT5-small" && python convert.py --dtype float32 --model $MODEL && python t5.py --model $MODEL --prompt "Life is like a box of chocolates."
Saving weights to google-byT5-small.npz
[INFO] Generating with T5...
Input:  Life is like a box of chocolates.
ÿ chocolates chocolates chocolates chocolates chocolates chocolates chocolates chocolates chocolates
Time: 0.33 seconds, tokens/s: 298.93
```
I also checked with …
> Add support for byt5 models

- llms/llama/llama.py
- llms/llama/requirements.txt
- llms/mistral/convert.py
- llms/mistral/mistral.py
- llms/mistral/requirements.txt
I faced an error with the config whilst converting the quantised instruct and base models.
AFAICT `rope_theta` is not used anywhere else.
> Fix conversion + inference errors. - Mistral

- llms/qwen/convert.py
Fix unsupported ScalarType BFloat16.
Env: Mac M1 Ultra
torch: torch-2.0.0, metal
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
File "/Volumes/v1/models/mlx-examples-main/llms/qwen/convert.py", line 110, in <module>
convert(args)
File "/Volumes/v1/models/mlx-examples-main/llms/qwen/convert.py", line 63, in convert
weights = {replace_key(k): v.numpy() for k, v in state_dict.items()}
File "/Volumes/v1/models/mlx-examples-main/llms/qwen/convert.py", line 63, in <dictcomp>
weights = {replace_key(k): v.numpy() for k, v in state_dict.items()}
TypeError: Got unsupported ScalarType BFloat16
```
Fix: almost the same as …
> QWEN: Fix unsupported ScalarType BFloat16

- cifar/requirements.txt
I noticed that CIFAR example is missing `numpy` in requirements.txt
> fix: Add numpy to CIFAR's requirements.txt

- whisper/benchmark.py
The script benchmark.py encounters an error when executed with the "large" model. This issue arises because the "large" model references "large-v3", which necessitates 128 Mel frequency bins. In contrast, all previous models were compatible with only 80 Mel frequency bins. Calling the transcribe() function performs inferencing correctly.
> [Whisper] Large-v3 requires 128 Mel frequency bins

- llms/deepseek-coder/README.md
- llms/deepseek-coder/convert.py
- llms/deepseek-coder/deepseek-coder.py
- llms/deepseek-coder/deepseek_coder.py
- llms/deepseek-coder/requirements.txt 
- llms/llama/convert.py
- llms/mistral/convert.py
- llms/mixtral/convert.py
- llms/phi2/convert.py
- llms/qwen/convert.py
The DeepSeek coder is currently the most popular state-of-the-art open source coding mode. It would be great to have the example to run it via mlx. I tried using the Llama example, but I encountered a few issues:
- It uses LlamaLinearScalingRotaryEmbedding, which is not supported by the current Llama example.
- It can't provide a SentencePiece model at the moment. Details can be found here: https://huggingface.co/deepseek-ai/deepseek-coder-33b-instruct/discussions/6
So, I thought it would be better to create a separate example for it instead of modifying the existing Llama example. However, I am happy to merge it with the Llama example if you think there is a good way to do so.
the scripts are adapted from Qwen and llama examples :)
> add deepseek coder example

- llms/deepseek-coder/deepseek_coder.py
While I was trying to upload the quantized deepseek code model to mlx-community, noticed the deepseek code example wouldn't load the quantized model because the quantization config popped up during loading of model arguments. The following "config.get("quantization", False)" will always return false, even for the quantized model.
> chore: fix the load quantization model for deepseek coder

- whisper/README.md
- whisper/benchmark.py
- whisper/convert.py
- whisper/test.py
- whisper/whisper/__init__.py
- whisper/whisper/load_models.py
- whisper/whisper/transcribe.py
Hi @awni 👋,
This PR introduces a feature to load customized MLX whisper models and integrates a conversion script for transforming the PyTorch checkpoint of OpenAI format into MLX. I believe this will be helpful for the community to easily convert and load other whisper models fine-tuned for low-resource languages in MLX.
Additionally, I've incorporated quantization into both the model conversion and loading processes.
It's working on my side, but might need additional review for modifications, doc, or testing. Thanks in advance!
> [Whisper] Load customized MLX model & Quantization

- llms/deepseek-coder/convert.py
- llms/deepseek-coder/deepseek_coder.py
Before consolidating all the models similar to llamas into the llama example, just make some minor changes in the DeepSeek example so that people can use it to run HF format models with autoTokenizer if they want to try out some hf format models. for example https://github.com/ml-explore/mlx-examples/issues/204
> chore: make the Deepseek example compatible with Yi models.

- llms/deepseek-coder/deepseek_coder.py
Disabling the fast tokenizer results in an error when running the example.
https://huggingface.co/mlx-community/deepseek-coder-6.7b-instruct-4-bit/discussions/1
> fix: deepseek coder tokenizer error

- .pre-commit-config.yaml
- gcn/main.py
- llms/deepseek-coder/convert.py
- llms/deepseek-coder/deepseek_coder.py
- llms/hf_llm/README.md
- llms/hf_llm/convert.py
- llms/hf_llm/generate.py
- llms/hf_llm/models.py
- llms/hf_llm/requirements.txt
- llms/llama/llama.py
- llms/speculative_decoding/decoder.py
- stable_diffusion/stable_diffusion/__init__.py
- stable_diffusion/stable_diffusion/unet.py
- whisper/benchmark.py
- whisper/convert.py
- whisper/test.py
Example supports
- Loading mistral/llama-style models directly from the Hugging Face Hub
- Converting models to different datatypes or quantized. Conversion script can upload and download models from the hub directly
> Support Hugging Face models

- llms/hf_llm/README.md
In `llms/hf_llm` the readme refers to `--hf-model` as a parameter to use to grab a model for conversion. This param doesn't exist, it's `--hf-path`. I've updated the readme to fix it.
> Update README.md to fix --hf-model param call.

- llms/hf_llm/generate.py
When using TinyLlama i've run into the case where we receive 0 tokens for a prompt. The user is shown an ambiguous error. This PR improves that to inform the user what has happened.
` 
python generate.py --model TinyLlama/TinyLlama-1.1B-Chat-v1.0 --prompt "What makes the sky blue?"
`
```
Fetching 8 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 114130.72it/s]
==========
File "/Users/ChristianOld/Documents/Projects/LLM/mlx-examples/llms/hf_llm/generate.py", line 93, in <module>
generate(model, tokenizer, args.prompt, args.max_tokens, args.temp)
File "/Users/ChristianOld/Documents/Projects/LLM/mlx-examples/llms/hf_llm …
```
> Handle receiving 0 tokens gracefully

- lora/lora.py
- lora/requirements.txt
Running the `convert.py` script in the lora example gives this error. I added numpy as a dependency.
```
python convert.py \
--torch-path mistral-7B-v0.1 \
--mlx-path mistral-7B-v0.1-mlx
```
yields this error:
```
File "/Users/lawrence.wu/github/mlx-examples/lora/convert.py", line 11, in <module>
import numpy as np
```
> add numpy as a requirement to run lora.py

- llms/phi2/README.md
- llms/phi2/convert.py
- llms/phi2/generate.py
- llms/phi2/phi2.py
Just try to make the phi2 example compatible with the phi2 model structure on HF, so people can directly use it without needing to convert. Additionally, given the small size of the model, it will be beneficial if people could directly load the full precision on the model without converting it first. 
Also, currently the open source LLM community prefers distributing fine-tuned models with lora weight merged, so keep the model structure consistent could avoid confusion for those distributing mlx fine-tuned models later.
But please feel free to dismiss this PR if it doesn't fit the purpose.
> refactor: make the phi2 example can be directly load the model from hf without convert needed

- llms/phi2/generate.py
- llms/phi2/phi2.py
Currently, the `generate.py` accidentally works because `generate` is called in `main` where `args` is within the scope of the main function.
> Fix use of undefined args in generate function in phi-2 example

- llms/hf_llm/README.md
- llms/hf_llm/generate.py
- llms/hf_llm/models.py
- lora/README.md
- lora/convert.py
- lora/fuse.py
- lora/lora.py
- lora/models.py
- lora/requirements.txt
- lora/utils.py
So now you can just run it with an HF repo or convert directly from an HF repo (and optionally upload).
Should work with a lot more models out of the box.
FYI right now this basically copies the convert from `hf_llm` and the model as well. In the future it might/probably makes sense to merge the two (especially if it gets subsumed into a package).
> Move lora example to use the same model format / conversion as `hf_llm`

- lora/README.md
- lora/lora.py
- lora/models.py
The custom tokenizer returns an mx array, and it will throw an error at https://github.com/ml-explore/mlx-examples/blob/main/lora/lora.py#L191 when trying to assign the mx array to the npx array.  also, the transformer tokenizer defaults include special tokens (bos, eos). According to https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.PreTrainedTokenizer.__call__.add_special_tokens, we don't really need the custom tokenizer for adding eos.
> fix(lora): tokenizer return incompatible mx array

- lora/fuse.py
Currently when one runs `python fuse.py` (assuming you have a `mlx_model` folder and a `adapters.npz` file.
It throws an error:
```
AttributeError: 'tokenizers.Tokenizer' object has no attribute 'save_pretrained'. Did you mean: 'from_pretrained'?
```
This PR fixes that.
> Fix Tokenizer save error.

- llms/hf_llm/generate.py
Similar to the one in [this PR](https://github.com/ml-explore/mlx-examples/pull/265).
The `generate` function uses `args` defined in the main function instead of using its function parameters.
> Fix use of undefiend args variable inside generate function in hf_llm example

- llms/hf_llm/convert.py
This PR is to add a local flag (-l, --local) to convert.py to enable the reading of HF Models already on the filesystem during a conversion operation. Currently the script has to download the model weights from HF directly before beginning the conversion to MLX format. 
Setting the --local flag disables uploads to huggingface during conversion as the hf_path argument would not specify the original model in the modelcard.
> Add -local flag to llms/hf_llm/convert.py for reading source HF models from filesystem.

- lora/lora.py
The prompt parameter was unused in the generate function. The function should use the passed in parameter instead of accessing `args.prompt` directly.
> prompt parameter

- cifar/README.md
- cifar/main.py
- cifar/requirements.txt
- cifar/resnet.py
This PR updates the CIFAR-10 ResNet example to use BatchNorm instead of LayerNorm. It is tested with mlx@026ef9a but should probably wait until https://github.com/ml-explore/mlx/pull/385 (remove `retain_graph` flag) appears in an official release. I am assuming, this will be in mlx 0.0.8. 
**Changes**
* Replaced ```nn.LayerNorm``` by ```nn.BatchNorm``` (test accuracy 0.807 after 100 epochs -> 0.833 after 30 epochs)
* Decreased default number of epochs from 100 to 30 (no improvement observed after approx. 25 epochs)
* Updated code comments and ```README.md```
* Updated ```requirements.txt``` to require ```mlx>=0.0.8```
**TODO**
> Updated CIFAR-10 ResNet example to use BatchNorm instead of LayerNorm

- bert/model.py
- llms/mlx_lm/models/phi2.py
- llms/setup.py
Annotating types using `list`, `tuple`, `dict` was introduced in python 3.9 and we are supporting from 3.8 . I guess since nobody complained I may be the last person using 3.8 .
I also bumped the version for the `mlx_lm` package so it can be uploaded to PyPI.
> Change tuple type definitions to use Tuple

- whisper/benchmark.py
- whisper/whisper/decoding.py
Executing `python benchmark.py` from the `whisper` directory yields
```tb
TypeError: DecodingOptions.__init__() got an unexpected keyword argument 'model_path'
```
This PR aims at fixing the issue by adding the appropriate placeholder for `model_path` in the `DecodingOptions` dataclass.
> Fix TypeError in whisper benchmark script

- llms/README.md
- llms/mlx_lm/convert.py
- llms/mlx_lm/models/mixtral.py
- llms/mlx_lm/utils.py
Added the example for Mixtral in HF format, in preparation to support LoRa/QLoRa for Mixtral. 
Uploaded the quant model [here](https://huggingface.co/mlx-community/Mixtral-8x7B-Instruct-v0.1-hf-4bit-mlx).
> feat(mlx_lm): add mixtral support in mlx_lm

- normalizing_flow/distributions.py
- normalizing_flow/flows.py
- normalizing_flow/main.py
This repo fails to run `pre-commit run --all-files` -- the `isort` hook fails. This PR fixes import order of the `normalizing_flow` example. After this, the repo will stay in a clean state.
By the way, we should add a `pull_request_template.md` file to this repo (like the one in mlx repo) so that contributors can be checked to run pre-commit hooks.
> Fix import order of the `normalizing_flow` example

- stable_diffusion/README.md
- stable_diffusion/image2image.py
- stable_diffusion/stable_diffusion/__init__.py
- whisper/whisper/load_models.py
closes #267 
U-Net requires that it's input is evenly divisible by the number of down / up blocks used as to guarantee that the skip connections can be added properly (avoiding shape mismatch). This is a well documented limitation [1](https://stackoverflow.com/questions/66028743/how-to-handle-odd-resolutions-in-unet-architecture-pytorch) [2](https://github.com/CompVis/stable-diffusion/issues/268) [3](https://github.com/CompVis/stable-diffusion/issues/191) of both UNet and SD. 
One solution is to just throw an error and let the user resize their input, another is to resize it for them. I followed the reasoning in [HuggingFace diffusers](https://github.com/huggingface/diffusers/blob/3be7c96e28495d2e45af5a5f8488a9bb41d66ccb/src/diffusers/image_processor.py#L787) which downsamples the input …
> Stable Diffusion: Input image downsampling

- lora/lora.py
Thank you for providing such a great library! 
Currently there is a risk of losing all progress in the event of an interruption during the finetuning process (`lora.py`). 
This pull request introduces the `--save-every N` argument, allowing to save adapter weights to the disk every N iterations during the finetuning process. This addition draws inspiration from a similar argument in [finetune in llama.cpp](https://github.com/ggerganov/llama.cpp/tree/master/examples/finetune).
I would appreciate any feedback.
> Add an argument to lora.py for saving the adapter file regularly

- lora/fuse.py
- lora/models/lora.py
- lora/utils.py
Quick and dirty implementation for supporting de-quant model during fusing. Also, updated the model weight to use HF format so that once the model is fused, it can be converted by gguf for more advanced quant support. 
PS: Once the Lora example is merged into mlx-lm, we can properly add this functionality and make the fused model can be directly loaded by the transformers library to support AWQ/GPTQ.
> feat(lora): add de-quantized support for fuse.py

- llms/mlx_lm/generate.py
Hi,
here is a small tweak to mlx_lm to be able to apply the defined chat_template (in tokenizer_config.json) when using it to quickly and correctly generate in cli.
I love your work, 😍
> add an option to apply the tokenizer chat template

- llms/mlx_lm/tuner/utils.py
- llms/mlx_lm/utils.py
As an alternative, when the fused model has slightly different text generation due to de-quantization, users can choose to load the adapter instead.  https://github.com/ml-explore/mlx-examples/issues/346
> chore(mlx-lm): add load model with adapter and fix bug in sample

- llms/mlx_lm/tuner/trainer.py
The current iterate_batches function will return a batch with the maximum length that the training set sentence has. This can cause a memory spike when the training dataset contains long sentences, which may crash the training process.
> chore(mlx-lm): truncate the input sentence to max seq len in lora iterate_batches

- llms/mlx_lm/utils.py
I purpose to change all usage of `time.time()` to [`time.perf_counter()`](https://docs.python.org/3/library/time.html#time.perf_counter) in `utils.py` for MLX-LM
`time.perf_counter` is more preferable when measuring and benchmarking since it is monotonic and higher precision clock compared to `time.time()`
Rough benchmarks with StableLM-2-Zephyr 1.6B model with this change
with time.time()
Prompt: 44.321 tokens-per-sec
Generation: 113.937 tokens-per-sec
with time.perf_counter()
Prompt: 192.664 tokens-per-sec
Generation: 117.253 tokens-per-sec
~~+300% on tokens/s for prompt~~ <- My bad 
+3% for tokens/s for generate
> Use better time for measuring tokens/second 🚀 

- llms/mlx_lm/tuner/utils.py
Add this helper so that we can restore the Lora layers to their original linear layers. This will allow us to switch between Lora layers without having to reload the entire model.
For example:
```python
from mlx_lm import load, generate
from mlx_lm.tuner.utils import apply_lora_layers, reset_lora_layers
model, tokenizer = load("mistralai/Mistral-7B-v0.1", adapter_file="adapter_1.npz")
response = generate(model, tokenizer, prompt="hello", verbose=True)
model = reset_lora_layers(model)
model = apply_lora_layers(model, adapter_file="adapter_2.npz")
response = generate(model, tokenizer, prompt="hello", verbose=True)
```
Given the current mlx loading speed is not optimal, this can be useful for applications that want to change adapters to fit different use cases.
> chore(mlx-lm): add reset lora layers helper

- llms/mlx_lm/utils.py
PR #342 inadvertently counted the number of characters in the resulting string as the number of tokens.  This inflated the tokens per second count by roughly a factor of 3 (when producing 100 tokens).
Before:
```
python -m mlx_lm.generate --model ~/Mistral-7B-v0.1-hf-4bit-mlx -m 20
==========
Prompt: hello
…
I’ve had my 1366 Samsung 24″ monitor for
==========
Prompt: 15.634 tokens-per-sec
Generation: 60.364 tokens-per-sec
```
After:
```
python -m mlx_lm.generate --model ~/Mistral-7B-v0.1-hf-4bit-mlx -m 20
==========
Prompt: hello
…
I’ve had my 1366 Samsung 24″ monitor for
==========
Prompt: 16.123 tokens-per-sec
Generation: 27.702 tokens-per-sec
```
> fix token count computation -- produced wrong tps measurements

- llms/mlx_lm/tuner/utils.py
@awni, I found this while working on the moe model stuff. I noticed that the lora weight doesn't apply to the gate and the weight distribution is almost identical to uniform. So, I dug a bit into the mlx-lm lora code and found out that we only replace the linear layer but never update the lora weight from adapters.
> fix(mlx-lm): apply lora layer doesn't update the lora weights

- llms/mlx_lm/lora.py
- llms/mlx_lm/utils.py
1. Supported models are already checked in the load_model function in utils, no need to repeat the check in lora
2. The checks in lora are not synchronized with those in utils
After deleting this part of the judgment, the Lora module will support the following model fine-tuning:
- stablelm_epoch
- qwen
- plamo
see [MODEL_MAPPING](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/utils.py#L19-L27) in mlx_lm utils.py .
Also solves issue #356
> LoRA: Remove unnecessary model type judgments

- llms/mlx_lm/lora.py
For the issue #407 
A new argument "--max_seq_length" has been added to the command-line parser and passed as a parameter to the main function of the lora.py script. This allows users to specify and control the maximum sequence length during training.
> Add max sequence length argument in lora.py

- llms/mlx_lm/utils.py
Due to the various different model formats, such as hf/pytorch/custom, it would be beneficial if we had a model weight metadata index. This way, we wouldn't have to download the model weight and check it locally. This approach also aligns with most of the Hugging Face model repository.
> chore(mlx-lm): add model weight index in save_weights

- llms/mistral/README.md
fixing broken link for mistral-7B-v0.1 model
Original change from mistral.ai:
https://github.com/mistralai/mistral-src/commit/8598cf582091a596671be31990448e0620017851
> fix-mistral-download-link

- llms/mlx_lm/tuner/trainer.py
The code was modified to create a checkpoints directory if it doesn't exist yet. Adapter weights are now saved to this checkpoints directory during the training iterations. Corrected indentation of Save adapter weights code because it was part of "if eval".
To implement checkpoints asked in #430 and fix a bug in the save adapters file.
> Add checkpoints directory for adapter weights

- llms/mlx_lm/tuner/utils.py
The parameter was passed incorrectly when checking the number of LoRA layers.
Related commit：#427
> fix: check LoRA layers number error

- llms/mlx_lm/lora.py
- llms/mlx_lm/tuner/trainer.py
In order to better monitor the details of the training process, we do some custom logic processing, and expose the training details to the caller in the form of a callback. For example, with this callback I can upload the training data to wandb (or other similar platforms).
For example, this PR #364.
If there are other better ways to do this, please feel free to suggest them.
> LoRA: add training callbacks

- llms/mlx_lm/lora.py
The argument name "--max_seq_length" was updated to "--max-seq-length" in the code to maintain a consistent naming convention across the program.
> Change argument name in lora.py

- llms/mlx_lm/models/mixtral.py
Mixtral models throw the following exception
```
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/mlx_lm/generate.py", line 119, in <module>
main(args)
File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/mlx_lm/generate.py", line 96, in main
model, tokenizer = load(args.model, tokenizer_config=tokenizer_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/mlx_lm/utils.py", line 278, in load
model = load_model(model_path)
^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/mlx_lm/utils.py", line 221, in load_model
model_class, model_args_class = …
```
> Mixtral: Fix non-default arg follows default exception

- lora/lora.py
I was using `lora.py` to train Mistral and accidentally used corrupted JSONL files. My traceback looked like this:
```
File "/Users/ovid/projects/llms/mlx-examples/lora/lora.py", line 328, in <module>
class Dataset:
train_set, valid_set, test_set = load(args)
^^^^^^^^^^
File "/Users/ovid/projects/llms/mlx-examples/lora/lora.py", line 142, in load
train, valid, test = (Dataset(Path(args.data) / f"{n}.jsonl") for n in names)
^^^^^^^^^^^^^^^^^^
File "/Users/ovid/projects/llms/mlx-examples/lora/lora.py", line 142, in <genexpr>
train, valid, test = (Dataset(Path(args.data) / f"{n}.jsonl") for n in names)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ovid/projects/llms/mlx-examples/lora/lora.py", line 130, in __init__
self._data = [json.loads(l) for l …
```
> Make it easier to know in which file we have bad JSON data

- llms/README.md
- llms/mlx_lm/LORA.md
- llms/mlx_lm/MERGE.md
- llms/mlx_lm/SERVER.md
- llms/mlx_lm/examples/merge_config.yaml
- llms/mlx_lm/merge.py
- llms/mlx_lm/models/llama.py
- llms/mlx_lm/models/mixtral.py
- llms/mlx_lm/models/olmo.py
- llms/mlx_lm/models/phi.py
- llms/mlx_lm/models/phixtral.py
- llms/mlx_lm/models/qwen2.py
- llms/mlx_lm/models/stablelm_epoch.py
- llms/mlx_lm/requirements.txt
- llms/setup.py
- lora/lora.py
Add a `mlx_lm.merge` command with initial support for spherical linear interpolation (slerp) model merging.
```
python -m mlx_lm.merge --config mlx_lm/examples/merge_config.yaml
```
Produces a new model which works pretty well.
Also closes #400
> Support for slerp merging models

- lora/lora.py
It fails on loading the dataset because `load_and_check` doesn't return anything.
> Bug fix in lora.py

- llms/mlx_lm/tuner/trainer.py
Optimized the TrainingCallback definition to put some information during training into the dict, increasing the flexibility of subsequent extensions. 
Also, the corresponding learning rate information is printed during training. Here's part of the printout from when I was training:
```
Training
Starting training..., iters: 800
Iter 1: Val loss 4.847, Val took 31.577s
Iter 10: Train loss 4.461, Learning Rate 1.000e-05, It/sec 0.608, Tokens/sec 677.748, Trained Tokens 11152,
Iter 20: Train loss 3.146, Learning Rate 1.000e-05, It/sec 0.529, Tokens/sec 594.284, Trained Tokens 22383,
Iter 30: Train loss 2.157, Learning Rate 1.000e-05, It/sec 0.495, Tokens/sec 544.745, Trained Tokens 33387,
Iter 40: Train loss 1.758, Learning Rate 1.000e-05, It/sec 0.472, Tokens/sec 525.752, Trained Tokens …
```
> LoRA: Add printing and callbacks for learning rate during training

- llms/mlx_lm/convert.py
- llms/mlx_lm/merge.py
- llms/mlx_lm/utils.py
Currently `load_model` in utils immediately evaluates the parameters which may be far from ideal for `merge` or `convert`. This adds the optional `lazy` parameter to `fetch_from_hub` and `load` as well as `donate_weights` to `save_weights` which allows us to only partially load a model when doing the above operations.
Sorry that you 'll have to scroll right to see the times. TL;DR: When memory is scarce things get much faster. I will report back with results from quantizing Mixtral on my puny M2 air.
Before
```
$ python -m mlx_lm.merge --config llms/mlx_lm/examples/merge_config.yaml    4.68s user 28.93s system 32% cpu 1:42.12 total
$ python -m mlx_lm.convert --hf-path /tmp/merged --mlx-path /tmp/merged-q4-test  2.64s user 9.67s system 43% cpu 27.997 total
$ python -m mlx_lm.convert …
```
> Lazy loading models for faster convert and merge

- llms/mixtral/mixtral.py
the create_cos_sin_theta went missing, however it's no longer needed, check https://github.com/ml-explore/mlx-examples/issues/465
this removes the custom class and adds the base param to the default RoPE instantation
> fix: remove custom rope

- llms/mlx_lm/__init__.py
- llms/mlx_lm/models/gemma.py
- llms/mlx_lm/models/layers.py
- llms/mlx_lm/models/llama.py
- llms/mlx_lm/models/mixtral.py
- llms/mlx_lm/models/olmo.py
- llms/mlx_lm/models/phi.py
- llms/mlx_lm/models/phixtral.py
- llms/mlx_lm/models/plamo.py
- llms/mlx_lm/models/qwen.py
- llms/mlx_lm/models/qwen2.py
- llms/mlx_lm/models/stablelm_epoch.py
- llms/mlx_lm/requirements.txt
Add pre-compiled normalizations for MLX LM. Speeds up generation time:
```
python -m mlx_lm.generate --model mlx-community/NeuralBeagle14-7B-4bit-mlx --prompt "Write a quick sort in C++"
```
Pre:
```
Prompt: 208.940 tokens-per-sec
Generation: 48.525 tokens-per-sec
```
Post:
```
Prompt: 214.853 tokens-per-sec
Generation: 52.489 tokens-per-sec
```
```
python -m mlx_lm.generate --model microsoft/phi-2 --prompt "Write a quick sort in C++"
```
Pre:
```
Prompt: 30.643 tokens-per-sec
Generation: 43.302 tokens-per-sec
```
Post:
```
Prompt: 34.124 tokens-per-sec
Generation: 48.204 tokens-per-sec
```
Requires shapeless compile in https://github.com/ml-explore/mlx/pull/687
> [mlx-lm] Add precompiled normalizations

- clip/convert.py
- clip/model.py
- clip/requirements.txt
- clip/test.py
Update the clip model format to HF format to make it easier for later use as a vision tower in the llava model.
close https://github.com/ml-explore/mlx-examples/issues/463
> chore(clip): update the clip example to make it compatible with HF format

- llms/mlx_lm/lora.py
Extracting the logic from `if __name__ == "__main__":` into a separate `run` function makes it easy to call the logic in the `lora.py` file from your own python scripts.
Below is a simple code example of my training scenario:
```py
import argparse
from mlx_lm import lora
from mlx_lm.tuner.trainer import TrainingCallback
def finetuning():
parser = lora.build_parser()
args = parser.parse_args(args=[])
args.model = "Qwen/Qwen1.5-1.8B-Chat"
args.train = True
wandb_callback = WandbCallback()
lora.run(args, training_callback = wandb_callback)
if __name__ == "__main__":
finetuning()
```
In addition to the command line, it's finally possible to fine-tune it by writing code.
> LoRA: Extract the run function for easy use in scripts file

- ACKNOWLEDGMENTS.md
- llms/mlx_lm/SERVER.md
- llms/mlx_lm/generate.py
- llms/mlx_lm/merge.py
- llms/mlx_lm/server.py
- llms/mlx_lm/utils.py
By default BaseHTTPRequestHandler serves the local directory as a website using the do_HEAD and do_GET methods. Should definitely not be the case. Although there are definitely bigger issues at hand if somebody runs these examples in production before looking at them, I'd still suggest having a security policy
Threw in some type hint fixes as a treat :)
> Prevent llms/mlx_lm from serving the local directory as a webserver

- llms/mlx_lm/generate.py
- llms/mlx_lm/utils.py
Add metadata format="pt" for safetensors so that model's are accessible to `transformers` users as well.
Tested locally for loading via transformers on a M3 Max MacBook Pro.
https://github.com/ml-explore/mlx-examples/issues/490
> Add metadata when saving safetensors

- llms/mlx_lm/tuner/trainer.py
Enable the passed in args.adapter_file to contain path information, such as passing in "build/adapters.npz". The storage path of the final file is as follows:
```
.
├── build
│   ├── adapters.npz
│   └── checkpoints
│       ├── 100_adapters.npz
│       └── 200_adapters.npz
```
> LoRA: adapter file Support path information

- llms/mlx_lm/utils.py
Use `textwrap.dedent` to allow proper indentation of strings.
**Current**
https://github.com/ml-explore/mlx-examples/blob/ae485633783a21204c74f97228fad251ac602e7b/llms/mlx_lm/utils.py#L440-L456 
**Suggested**:
```py
from textwrap import dedent
def somefunc():
...
text = dedent("""
some text...
goes here.
...
""")
...
```
> fix: string indentation with `textwrap.dedent`

- llms/mlx_lm/server.py
Address: https://github.com/ml-explore/mlx-examples/pull/498#issuecomment-1974960089, just in case there is a release for mlx-lm. We won't release the broken script.
> chore(mlx-lm): fix broken server.py script

- llms/mlx_lm/models/starcoder2.py
address https://github.com/ml-explore/mlx-examples/pull/502#issuecomment-1975121697
> chore(mlx-lm): add missing model_type for starcoder2

- ACKNOWLEDGMENTS.md
- llms/mlx_lm/models/starcoder2.py
This PR updates the config to match the HF Starcoder config and changes GQA to use repeat instead of concatenate as suggested here https://github.com/ml-explore/mlx-examples/pull/443. 
@mzbac the PR is ready!
https://github.com/ml-explore/mlx-examples/pull/502#issuecomment-1975063865
> Starcoder2: Update config and change GQA to use repeat

- llms/mlx_lm/utils.py
Print the URL address of the uploaded Hugging Face repository, which can be opened by clicking on the link as a quick jump in the terminal, as follows:
> Print huggingface repo url

- llms/mlx_lm/models/gemma.py
- llms/mlx_lm/models/llama.py
- llms/mlx_lm/models/qwen2.py
- llms/mlx_lm/models/stablelm.py
- llms/mlx_lm/models/starcoder2.py
- llms/mlx_lm/requirements.txt
- llms/mlx_lm/version.py
Ran on an M1 Max
```
python -m mlx_lm.generate --model mlx-community/NeuralBeagle14-7B-4bit-mlx --max-tokens 500 --prompt "write a very long quicksort"
```
Original:
```
Prompt: 138.752 tokens-per-sec
Generation: 26.673 tokens-per-sec
```
SDPA:
```
Prompt: 136.871 tokens-per-sec
Generation: 29.504 tokens-per-sec
```
Text was identical in both cases. Probably would see a bigger benefit if I push the context size even more. I'll try so on another machine.
(Also closes #504)
> [mlx-lm] Use sdpa in llama / mistral model

- .circleci/config.yml
- llms/mlx_lm/examples/lora_config.yaml
- llms/mlx_lm/lora.py
- llms/mlx_lm/tuner/lora.py
- llms/mlx_lm/tuner/trainer.py
- llms/mlx_lm/tuner/utils.py
- llms/tests/test_lora.py
- llms/tests/test_utils.py
In general, it would be useful for the LoRa tuner and linear_to_lora_layers in mlx_lm.tuner.utils in particular to allow more control over how LoRa is applied (the ability to specify the rank and alpha, for example).  This PR is for the basic ability to indicate via CLI option (-l/--lora-all-linear) that LoRa is applied to **all** linear transformer block layers (adding the application of LoRa to k_proj and o_proj).  Currently, it only does this for the following models:
- llama
- mistral
- mixtral
- gemma
- phi
- plamo
- qwen2
- stablelm
- starcoder2
This is mainly motivated by the finding of authors of the QLoRa [paper](https://arxiv.org/abs/2305.14314)
> that the most critical LoRA hyperparameter is how many LoRA adapters are used in total and that **__LoRA on all linear transformer …
> LoRA on all linear transformer block layers

- bert/model.py
I was using MLX to do some masked language modeling using bert model example, and I wasn't able to
```optimizer.update(model.trainable_parameters(), grads)```
Like how it is done in the MLP example documentation [here](https://ml-explore.github.io/mlx/build/html/examples/mlp.html)
After adding ```super().__init__()``` to both the ```BERT``` class and the ```BertEmbeddings``` my training loop proceeded.
> bert encoder inherits from nn.Module now

- t5/t5.py
As per the [mesh tensorflow](https://github.com/tensorflow/mesh/blob/fa19d69eafc9a482aff0b59ddd96b025c0cb207d/mesh_tensorflow/transformer/transformer.py#L586) and [transformers](https://github.com/huggingface/transformers/blob/00c1d87a7d5c8dfb4554370983b5a3f7c069edd7/src/transformers/models/t5/modeling_t5.py#L1771) implementations, scaling should be done when the embeddings are tied, not the other way round.
> T5: Fix scaling when embeddings are tied

- llms/mlx_lm/LORA.md
- llms/mlx_lm/lora.py
- llms/mlx_lm/requirements.txt
- llms/mlx_lm/tuner/datasets.py
- llms/tests/test_datsets.py
Supports OpenAI's fine-tuning format. Currently, both methods are supported. The format is as follows:
Chat format:
```
{"messages": [{"role": "system", "content": "Marv is a factual chatbot that is also sarcastic."}, {"role": "user", "content": "What's the capital of France?"}, {"role": "assistant", "content": "Paris, as if everyone doesn't know that already."}]}
{"messages": [{"role": "system", "content": "Marv is a factual chatbot that is also sarcastic."}, {"role": "user", "content": "Who wrote 'Romeo and Juliet'?"}, {"role": "assistant", "content": "Oh, just some guy named William Shakespeare. Ever heard of him?"}]}
{"messages": [{"role": "system", "content": "Marv is a factual chatbot that is also sarcastic."}, {"role": "user", "content": "How far is the Moon from Earth?"}, {"role": …
```
> Support for OpenAI’s fine-tuning dataset format

- bert/README.md
- bert/convert.py
- bert/model.py
- bert/test.py
I changed some things that were hard coded before that can be retrieved from `config.json` to enable more models with the `BertForMaskedLM` architecture. I tested it with some other models, e.g.
> python convert.py --bert-model "unitary/toxic-bert" --mlx-model weights/toxic-bert.npz    
> python test.py --bert-model "unitary/toxic-bert" --mlx-model "weights/toxic-bert.npz" --text "Hello World!" 
> Tests pass :)
It should in theory also work with RoBERTa models, but I haven't quite gotten it to run yet.
> Enable more BERT models

- llms/mlx_lm/utils.py
It isn't always clear when HF uploads have been deprecated by subsequent changes to mlx/mlx-lm.  Adding version information to the HF model card can help with this.
> Add mlx-lm version information to HF model card

- llms/mlx_lm/convert.py
- llms/mlx_lm/utils.py
This feature allows us to dequantize a 4-bit-quantized model.
> add dequantize option to mlx_lm/convert.py

- llms/mlx_lm/server.py
Response should set finish_reason to `stop` if the response is complete, and `length` if not.
```
{'id': 'chatcmpl-e1df9ab4-1140-484c-8bbb-ad35363a5876',
'system_fingerprint': 'fp_60cb9d1c-c9da-473f-97ca-d92e45a4ea3a',
'object': 'chat.completions',
'model': 'berkeley-nest/Starling-LM-7B-alpha',
'created': 1710478081,
'choices': [
{'index': 0,
'logprobs': None,
'finish_reason': 'length',
'message': {
'role': 'assistant',
'content': 'After six hours, Karen loses a total of 12 pounds of water and 12 * (2/3) = 8 pounds of food. Therefore, she is carrying 20 + 10 + 20 - 12 - 8 = 30 pounds of weight after six hours. \n\nQuestion: A rectangular'
}
}
],
'usage': {'prompt_tokens': 318, 'completion_tokens': 75, 'total_tokens': 393}
}
```
> Set finish_reason in server response

- llms/mlx_lm/generate.py
The LLM community seems to be moving towards the standard chat template, with many models starting to use the default chat template. Enabling the default chat template for mlx-lm may be more beneficial. Additionally, users can always manually disable the chat template using the `--ignore-chat-template` flag.
@awni, please feel free to close this PR if you feel it does not fit the purpose.
> chore(mlx-lm): enable to apply default chat template

- llms/mlx_lm/sample_utils.py
- llms/mlx_lm/utils.py
- llms/tests/test_sample_utils.py
The top_p is supposed to sort prob in **ascending** order and select the cumulative token prob above the threshold. The current implementation works because we have a bug in reversing the sorted prob, which accidentally makes sorted prob in the correct order. So, it's better to fix the implementation to reduce the confusion.
> chore(mlx-lm): fix the top_p implementation.

- llms/mlx_lm/utils.py
Simple heuristic speeds up token generation considerably for long generations. I haven't detected any change in output yet.
On M2 Ultra
```
python -m mlx_lm.generate --model  mlx-community/NeuralBeagle14-7B-4bit-mlx --prompt "Write a quick sort in C++" --max-tokens 500 --temp 0.0
```
Pre: `85.823`
Post: `90.657`
> Partially stream de-tokenization

- llms/mlx_lm/tuner/lora.py
Should speed up inference with adapters. Since adapters are in fp32 we would up cast at the first LoRA layer and then never downcast which slows things down a lot.
I will report some training runs to be sure there is minimal change there.
Edit: see comment below. Looks like validation loss is unaffected and training speed is noticeably improved 🚀
> Cast around lora adapters

- llms/mlx_lm/sample_utils.py
- llms/tests/test_sample_utils.py
Just realized that the sorted probs indexing introduced a new dimension, so we have to squeeze it out. Also, update the test to cover the shape changes.
> fix(mlx-lm): sorted probs in top_p implementation.

- llms/mlx_lm/models/cohere.py
- llms/mlx_lm/version.py
Use the qk norm param to work with cohere plus.
Machine setting:
```
sudo sysctl iogpu.wired_lwm_mb=100000
```
Command for generation:
```
python -m mlx_lm.generate --model mlx-community/c4ai-command-r-plus-4bit --prompt "Write a quicksort in c++" --temp 0.0 --max-tokens 256 --use-default-chat-template
```
Command for QLoRA:
```
python -m mlx_lm.lora --model mlx-community/c4ai-command-r-plus-4bit --data ../lora/data --train --iters 1000  --batch-size 1 --lora-layers 16
```
> Fix for cohere plus

- llms/mixtral/mixtral.py
- llms/mlx_lm/models/dbrx.py
- llms/mlx_lm/models/mixtral.py
- llms/mlx_lm/models/phixtral.py
Fixes an obo error in the argpartition call but it was not really a bug since our argpartition uses sort. Better to fix though.
> Fix argpartition call in  Mixtral and other MOES

- bert/model.py
- cifar/resnet.py
- clip/model.py
- gcn/main.py
- llms/gguf_llm/models.py
- llms/mixtral/mixtral.py
- llms/mlx_lm/models/dbrx.py
- llms/mlx_lm/tuner/trainer.py
- llms/speculative_decoding/decoder.py
- llms/speculative_decoding/main.py
- llms/speculative_decoding/model.py
- llms/tests/test_lora.py
- lora/lora.py
- lora/models.py
- speechcommands/kwt.py
- speechcommands/main.py
- stable_diffusion/stable_diffusion/model_io.py
- whisper/benchmark.py
- whisper/test.py
- whisper/whisper/audio.py
- whisper/whisper/decoding.py
- Removed unused Python imports in the following files (example format: **file_name:line_number imported_pkg**):
- bert/model.py:10: tree_unflatten
- bert/model.py:2: dataclass
- bert/model.py:8: numpy
- cifar/resnet.py:6: Any
- clip/model.py:15: tree_flatten
- clip/model.py:9: Union
- gcn/main.py:8: download_cora
- gcn/main.py:9: cross_entropy
- llms/gguf_llm/models.py:12: tree_flatten, tree_unflatten
- llms/gguf_llm/models.py:9: numpy
- llms/mixtral/mixtral.py:12: tree_map
- llms/mlx_lm/models/dbrx.py:2: Dict, Union
- llms/mlx_lm/tuner/trainer.py:5: partial
- llms/speculative_decoding/decoder.py:1: dataclass, field
- llms/speculative_decoding/decoder.py:2: Optional
- llms/speculative_decoding/decoder.py:5: mlx.nn
- llms/speculative_decoding/decoder.py:6: numpy
- …
> Removed unused Python imports

- llms/README.md
- llms/mlx_lm/LORA.md
- llms/mlx_lm/MERGE.md
- llms/mlx_lm/SERVER.md
- llms/mlx_lm/convert.py
- llms/mlx_lm/generate.py
- llms/mlx_lm/lora.py
- llms/mlx_lm/merge.py
- llms/mlx_lm/server.py
- llms/setup.py
This PR create executable commands on installation: `mlx_lm.generate, mlx_lm.lora, mlx_lm.server, mlx_lm.merge, mlx_lm.convert`, without having to invoke `python -m`.
This is especially helpful to use with global installation tool such as `pipx, condax, pixi global` etc as user won't have to manage their virtualenv manually.
My motivation for this is that I want a quick way to startup a local language server like ollama, but using mlx.
> Create executables for generate, lora, server, merge, convert

- llms/mlx_lm/server.py
- llms/mlx_lm/utils.py
- llms/tests/test_server.py
There are two changes breaking the current server.py. The async eval now returns the token item instead of just the token, causing the "item" method to not be found. Additionally, the entryscript is making the global MODEL and TOKENIZER not found. Therefore, this PR is fixing those two issues and also adapting to use the new tokenizer wrapper's detokenizer to improve decoding speed.
> fix(mlx-lm): broken server.py

- llms/gguf_llm/models.py
- llms/llama/convert.py
- llms/llama/llama.py
- llms/llama/requirements.txt
- llms/mistral/convert.py
- llms/mistral/mistral.py
- llms/mistral/requirements.txt
- llms/mixtral/convert.py
- llms/mixtral/mixtral.py
- llms/mixtral/requirements.txt
- llms/mlx_lm/models/cohere.py
- llms/mlx_lm/models/gemma.py
- llms/mlx_lm/models/olmo.py
- llms/mlx_lm/models/qwen2.py
- llms/mlx_lm/models/starcoder2.py
- llms/mlx_lm/requirements.txt
- llms/mlx_lm/tokenizer_utils.py
- llms/mlx_lm/tuner/trainer.py
- llms/mlx_lm/utils.py
- llms/mlx_lm/version.py
- llms/tests/test_models.py
- stable_diffusion/image2image.py
- stable_diffusion/requirements.txt
- stable_diffusion/txt2image.py
- whisper/convert.py
- whisper/requirements.txt
- whisper/whisper/load_models.py
- whisper/whisper/whisper.py
As title. Relies on https://github.com/ml-explore/mlx/pull/994
> Quantize embedding / Update quantize API

- llms/mlx_lm/server.py
I misunderstood how the new detokenizer works, didn't realize that detokenizer.finalize() would force decoding of the current token, which breaks the unicode decoding that requires more than 1 token.
before:
after:
> fix(mlx-lm): unicode decoding in server.py

- lora/fuse.py
- lora/utils.py
Was unable to load the fused model on an ubuntu environment. Was able to load it when I changed save_safetensors metadata to 'pt' (there was a related [GH](https://github.com/ml-explore/mlx/issues/633) issue I believe) and produced model.safetensors.index.json. If this patch is not optimal, would still be better imo to let users know about this incompatibility, until it's fixed.
> Load fused model with transformers

- llms/speculative_decoding/model.py
A `Tuple` is missing in this type annotation.
> Fix incorrect type annotation

- llms/mlx_lm/utils.py
- lora/utils.py
This PR uses an experimental feature in the HuggingFace API that creates multiple commits per upload. It is very convenient for big models with multiple files. It also allows for resuming the upload if something fails by simply re-running the command. I've tested it with `convert`, it looks [like this](https://huggingface.co/mlx-community/zephyr-orpo-141b-A35b-v0.1-8bit/discussions/2).
> Upload uses multi_commits when uploading to HF

- llms/gguf_llm/README.md
- llms/gguf_llm/models.py
The official phi-3-mini-4k-instruct gguf weight is currently unsupported (of type array(15, dtype=uint32)) by mlx, I uploaded a supported 4bit quantized gguf weight, download here: https://huggingface.co/Jaward/phi-3-mini-4k-instruct.Q4_0.gguf.
Also included a print of model info and quant type.
> Add Supported Quantized Phi-3-mini-4k-instruct gguf Weight

- llms/mlx_lm/tuner/trainer.py
- llms/tests/test_lora.py
Fixing the issue where setting `-1` for the number of validations does not evaluate the full validation set.
> chore(mlx-lm): fix the number of validation batches configuration.

- llms/mlx_lm/models/llama.py
The current implementation of the mask assumes the attention matrix is square, which is true if there is no cache. However, if one wishes to produce multiple tokens at a time, such as in speculative decoding implementations, a rectangular mask is necessary.
This change pads the bottom of the mask with zeros so multi-token decoding with a cache works correctly.
> Pad mask with zeros for non-square attention matrices

- llava/generate.py
Some other flavors of llava models have different EOS tokens, and noticed this example didn't have a way to override it. So I added an optional parameter. 
**example without custom EOS**
```python
➜  llava git:(main) ✗ python generate.py \
--model xtuner/llava-phi-3-mini-hf \
--image "http://images.cocodataset.org/val2017/000000039769.jpg" \
--prompt "USER: <image>\nWhat are these?\nASSISTANT:" \
--max-tokens 128 \
--temp 0
USER: <image>
What are these?
ASSISTANT:
These are two cats sleeping on a pink couch.<|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|> …
```
> Add optional EOS token for llava example

- llms/mlx_lm/tuner/trainer.py
- llms/mlx_lm/utils.py
For easy editing of the loaded model configuration (e.g., increasing RoPE base frequency or PI). Example:
```python
from mlx_lm import load, generate
model, tokenizer = load("mlx-community/Phi-3-mini-4k-instruct-4bit-no-q-embed", model_config={"rope_theta":50000.0})
response = generate(model, tokenizer, prompt)
```
Output with default rope_theta of 10000.0:
Output with modified rope_theta:
> Add `model_config` parameter to `load()` and `load_model()`

- lora/lora.py
- lora/utils.py
Support `--add_eos_token` argument to empower users to control the addition of the eos token during LoRA training, addressing issues like endless text generation.
see #756
> Support `--add_eos_token` argument within Lora training

- llms/mlx_lm/utils.py
Added proper error handling to `load` and `get_model_path` by adding a dedicated exception class, because when the local path is not right, it still throws the huggingface `RepositoryNotFoundError`, which is not fully informative to the end user, they might have just entered their local path wrong by one character.
> fix: Added dedicated error handling to load and get_model_path

- llms/mlx_lm/fuse.py
- llms/mlx_lm/models/mixtral.py
- llms/mlx_lm/models/phixtral.py
- llms/mlx_lm/models/qwen2_moe.py
- llms/mlx_lm/models/switch_layers.py
- llms/mlx_lm/tuner/lora.py
- llms/mlx_lm/tuner/utils.py
- llms/mlx_lm/utils.py
Implements all MoEs with the new `mx.block_sparse_mm` and `mx.block_sparse_qmm` (the latter is at https://github.com/ml-explore/mlx/pull/1124 ).
One notable change is in the quantization predicate which accepts modules that define `to_quantized()` and delegates the check for the existence of quantized weights to the module using `is_quantized()`. This allows us to define `SwitchMLP` for each model and a quantized equivalent and auto convert to the quantized one.
Before
```
Qwen1.5-MoE-A2.7B-Chat     : 56.3 tps
Mixtral-8x7B-Instruct-v0.1 : 40.3 tps
phixtral-4x2_8             : 47.2 tps
```
After
```
Qwen1.5-MoE-A2.7B-Chat     : 121.7 tps
Mixtral-8x7B-Instruct-v0.1 :  59.3 tps
phixtral-4x2_8             :  92.8 tps
```
> Block sparse MM MoEs

- llms/mlx_lm/models/base.py
- llms/mlx_lm/models/gpt_bigcode.py
- llms/mlx_lm/models/llama.py
- llms/mlx_lm/tuner/utils.py
This PR adds support for openELM.
Todo:
> Add support for ibm granite

- llms/mlx_lm/examples/lora_config.yaml
- llms/mlx_lm/lora.py
- llms/mlx_lm/tuner/__init__.py
- llms/mlx_lm/tuner/dora.py
- llms/mlx_lm/tuner/lora.py
- llms/mlx_lm/tuner/trainer.py
- llms/mlx_lm/tuner/utils.py
- llms/mlx_lm/version.py
- llms/tests/test_lora.py
- llms/tests/test_tuner_utils.py
Extract the `load_with_lora` function for easy use in other files.
> LoRA: Extract small function

- llms/mlx_lm/models/gpt2.py
- llms/mlx_lm/tuner/utils.py
- llms/tests/test_models.py
Wanted to share support for the HF OpenAI GPT-2 models (gpt2, gpt2-medium, gpt2-large, and gpt2-xl) in case there is any interest for it to be merged. The existing gpt_bigcode support was utilized; however, model sanitization with the HF OpenAI GPT-2 models is different enough because of the unneeded attention "bias" layers & needing to transpose the Conv1D weights as they are stored along with some other gymnastics. There is potential to merge into 1 model implementation with gpt_bigcode, but IMO that would unnecessarily complicate both model implementations.
> GPT2 Support

- llms/README.md
- llms/mlx_lm/__init__.py
- llms/mlx_lm/generate.py
- llms/mlx_lm/utils.py
Add streaming feature to text generation function `generate`
- Implemented an internal generator `_generate` to handle both streaming and non-streaming text generation modes.
- Updated the `generate` function to return a generator when streaming is enabled, and the full generated text when streaming is disabled.
> mlx_lm: Add Streaming Capability to Generate Function

- llms/mlx_lm/lora.py
The current released version of `mlx_lm` (0.14.3) from https://pypi.org/project/mlx-lm/#files contains a bug in the `lora.py` file. When attempting to load pretrained adapters using either the `--resume_adapter_file` command-line argument or the `resume_adapter_file` option in the `lora_config.yaml` file, a `NameError` is raised because the variable `resume_adapter_file` is not defined.
```shell
$ mlx_lm.lora --config lora_config.yaml
Loading configuration file lora_config.yaml
Loading pretrained model
Fetching 11 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 93966.08it/s]
Special tokens have been added in the …
```
> Fix NameError in lora.py when loading pretrained adapters

- llms/mlx_lm/models/llama.py
mypy complains about the assigning of value `None` to the field of type `int`.
> Correct type annotation of llama.ModelArgs.num_key_value_heads

- llms/mlx_lm/models/llama.py
The source code accesses `cache.offset` and `cache.update_and_fetch`, which belong to `base.KVCache`, so it seems that we should update the type annotation of `cache` from `Tuple[mx.array, mx.array]` into `base.KVCache`.
After doing so, mypy does not longer complain about the type annotation.
> Correct the type annotation of cache in llama.py

- llms/mlx_lm/models/phi3.py
- llms/mlx_lm/models/su_rope.py
This Pull Request introduces an implementation of the su-RoPE used by some of the Phi-3 language models. 
Key Changes:
- Supports the non-traditional RoPE variant used by Phi-3 (the traditional argument is included but unused).
- Handles query and key rotations separately, matching the current mlx-lm implementation.
Future Optimization:
- The code structure allows for easy modification to perform both query and key rotations in a single call for potential efficiency gains.
> Su-RoPE(Rotary Position Embedding) for Phi-3

- llms/mlx_lm/server.py
Hi,
I am not sure if that is of general interest, but I thought I'd submit it in case it's useful.
I had to tweak the server a little to get it to interact with dspy following the following comment https://github.com/stanfordnlp/dspy/issues/385#issuecomment-1998939936.
The two tweaks are to (1) relax the validation and convert from int to float as needed, (2) to work around some chat template not taking the system role (such as Google Gemma's chat template).
can try it out with:
```sh
python -m server --model mlx-community/gemma-1.1-7b-it-4bit --port 1143
```
modulo patching the relative imports in server.py
```
-from .tokenizer_utils import TokenizerWrapper
-from .utils import generate_step, load
+from mlx_lm.tokenizer_utils import TokenizerWrapper
+from mlx_lm.utils import …
```
> Tweaks to run dspy-produced calls to the server, with gemma template.

- llms/mlx_lm/models/qwen2.py
- llms/mlx_lm/models/qwen2_moe.py
- llms/mlx_lm/models/starcoder2.py
Before this change, we have
```
❯ mypy \
--explicit-package-bases \
--ignore-missing-imports \
. | grep 'qwen2'
llms/mlx_lm/models/qwen2_moe.py:25: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
llms/mlx_lm/models/qwen2_moe.py:82: error: "Tuple[Any, Any]" has no attribute "offset"  [attr-defined]
llms/mlx_lm/models/qwen2_moe.py:83: error: "Tuple[Any, Any]" has no attribute "offset"  [attr-defined]
llms/mlx_lm/models/qwen2_moe.py:84: error: "Tuple[Any, Any]" has no attribute "update_and_fetch"  [attr-defined]
llms/mlx_lm/models/qwen2.py:19: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
llms/mlx_lm/models/qwen2.py:55: error: Unsupported operand types for / ("int" and …
```
> Fix mypy errors with models/{qwen2,qwen2_moe,startcoder2}.py

- llms/mlx_lm/server.py
- llms/tests/test_server.py
As title. Basically moves the model loading logic into the `ModelProvider`. The POST handler passes the `requested_model` to the model provider to load that model instead of always using the default one.
It should be completely backwards compatible even wrt to when the default model will be loaded.
> Server loads the model on demand from the request

- llms/mlx_lm/models/gemma2.py
Gemma was talking nonsense - so I figured out it was due to not having logit softcapping and precision issues causing NaNs (so I implemented the softcapping and added more float32 inference). gemma-27b-it-4bit now works flawlessly (or near-flawlessly, no sliding-window attention).
Will post more comparisons later - but right now, try the model available on mlx-community with this pr and the current mlx branch. The difference will be clear (as the current implementation just outputs pad).
> Add logit soft capping to gemma, and fix precision issues

- llms/mlx_lm/models/recurrent_gemma.py
- llms/mlx_lm/server.py
1. Launch server:
```
mlx_lm.server
```
2. Make request:
```python
import openai
openai_client = openai.OpenAI(api_key = "placeholder-api", base_url="http://localhost:8080")
response = openai_client.chat.completions.create(
model='mlx-community/Meta-Llama-3-8B-Instruct-4bit',
messages=[
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": f"Say this is a test!"},
],
)
```
Closes #875 
Also added a couple fixes for RecurrentGemma 9B
> Fix server for `openai` package

- llms/README.md
- llms/mlx_lm/examples/generate_response.py
- llms/mlx_lm/requirements.txt
The example is meant to extend the [README](https://github.com/a-wozniakowski/mlx-examples/tree/main/llms), whereby it:
- uses a [checkpoint](https://huggingface.co/mlx-community/Mixtral-8x22B-Instruct-v0.1-4bit) from the mlx-community
- loads the model and tokenizer with `load`
- transforms a prompt into a chat template with the `apply_chat_template` method of the tokenizer
- passes optional arguments into `generate`, which show how to control the generation process
> Example of response generation with optional arguments

- lora/lora.py
The CLI arguments allow you to validate with the entire dataset by passing a negative one value, but this quickly results in a division by zero `NaN` to appear as the validation score!
Using `-1` for the `--val-batches` argument should run the validation process using all available mini batches from the dataset.
Upon starting a `--train` with `--val-batches -1`, the process quickly kicks back a `NaN` for the validation score!
Check if the `--val-batches` got a `-1` and if so, re-assign it to be the complete size of the data (validation) set.
I tested this two-line change locally and it works.
* I have learned that `mlx_lm` offers more (in the sibling directory of this repo), although I still found the study of this file helpful.
* I was doing a "memorization" training, such that …
> Validation with full data set, results in NaN validation score

- llms/mlx_lm/server.py
Fixes #887 
If a model is loaded, then you load an invalid model and then reload the old model, the key is not updated.. so it thinks it has the old model correctly loaded even though the model and tokenizer were cleared.
> Keep the LM server in a valid state

- clip/convert.py
This commit adds a new command-line option for `lora/convert.py` as `--force-download` to the `fetch_from_hub` function in `utils.py`. When this option is provided, the model will be forcefully downloaded from Hugging Face, even if it already exists locally. This can be useful when there are updates to the model that need to be fetched.
> feat: Add support for force downloading the model from Hugging Face

- llms/mlx_lm/utils.py
- llms/tests/test_utils_load_model.py
This will enable the community to utilize most of the utility functions but implement their own variant of the model, e.g. the sharding model https://github.com/mzbac/mlx_sharding/blob/main/server/server.py#L25-L66 , without having to copy the source code from mlx_lm.
@awni, please feel free to close this if you don't think it fits the purpose.
> support load model by custom get_model_classes

- llms/mlx_lm/models/base.py
- llms/mlx_lm/models/cohere.py
- llms/mlx_lm/models/dbrx.py
- llms/mlx_lm/models/deepseek_v2.py
- llms/mlx_lm/models/gemma.py
- llms/mlx_lm/models/gemma2.py
- llms/mlx_lm/models/gpt2.py
- llms/mlx_lm/models/gpt_bigcode.py
- llms/mlx_lm/models/gpt_neox.py
- llms/mlx_lm/models/internlm2.py
- llms/mlx_lm/models/llama.py
- llms/mlx_lm/models/minicpm.py
- llms/mlx_lm/models/mixtral.py
- llms/mlx_lm/models/olmo.py
- llms/mlx_lm/models/openelm.py
- llms/mlx_lm/models/phi.py
- llms/mlx_lm/models/phi3.py
- llms/mlx_lm/models/phi3small.py
- llms/mlx_lm/models/phixtral.py
- llms/mlx_lm/models/plamo.py
- llms/mlx_lm/models/qwen.py
- llms/mlx_lm/models/qwen2.py
- llms/mlx_lm/models/qwen2_moe.py
- llms/mlx_lm/models/stablelm.py
- llms/mlx_lm/models/starcoder2.py
This PR introduces minor changes that help use mlx-lm's models with
advanced decoding techniques such as speculative decoding and
prompt cache reuse. They are the based on my experience building
https://github.com/otriscon/llm-structured-output on top of mlx-lm.
Currently, each model implementation in `mlx-examples/llms/models` has ad-hoc
code to create a mask for the attention mechanism. This usually takes the form:
```
mask = None
if h.shape[1] > 1:
mask = nn.MultiHeadAttention.create_additive_causal_mask(h.shape[1])
mask = mask.astype(h.dtype)
```
This creates a mask when the input consists of more than one token, but this
code assumes the multi-token input is at the beginning of inference.
If, for example, we are evaluating multiple tokens because of speculative
decoding or prompt …
> Unify attention mask in LLMs

- llms/mlx_lm/server.py
Usage stats are now available when using streaming in the Chat Completions API. Set `stream_options: {"include_usage": true}` and you’ll see an extra chunk at the end of the stream with usage populated.
- twitter/x: https://x.com/OpenAIDevs/status/1787573348496773423
- cookbook: https://cookbook.openai.com/examples/how_to_stream_completions#4-how-to-get-token-usage-data-for-streamed-chat-completion-response
- api docs: https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options
use
```bash
curl http://localhost:8080/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
"model": "Qwen/Qwen2-0.5B-Instruct-MLX",
"stream":true,
"stream_options":{"include_usage":true},
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"role": …
```
> Server: support stream_options

- llms/mlx_lm/SERVER.md
- llms/mlx_lm/server.py
- llms/tests/test_server.py
Right now to add in adapters once the server has started, we need to restart the server. I just minimally changed the ```load``` function and the ```do_POST``` function in server.py, adding in an optional argument to load so that the user can add in an adapter during runtime. I tested it with by starting a server with Mistral and then changing the model to Phi-3B w/ LoRa adapters with a POST request.
**I did not add the restriction that adapters need to be in the current working directory **
> Adapters loading

- llms/mlx_lm/server.py
- llms/tests/test_server.py
When streaming using mlx_lm/server.py we should predict potential stop sequence matches, and generate tokens until we know that there is no match. This prevents the server from sending parts of a stop sequence to the client before it finds the match. 
Fixes #524 
My implementation adds a new function called "sequence_overlap" which checks how much sequence 1 has overlap with sequence 2. It checks for larger overlaps first, and returns the overlap as an integer.
The server checks for overlaps, and generates more tokens before allowing the server to send them.
```python
if any((sequence_overlap(tokens, sequence) for sequence in stop_id_sequences)):
continue
```
The sequence_overlap implementation can be tested with this example:
```python
from typing import Sequence
def sequence_overlap(s1: …
```
> Predict stop sequence matches during streaming

- README.md
- llms/mlx_lm/gguf.py
- whisper/convert.py
- whisper/mlx_whisper/version.py
- whisper/mlx_whisper/whisper.py
- whisper/test.py
For example:
```
python convert.py --torch-name-or-path distil-whisper/distil-large-v2
```
And then use the model in the regular way.
Closes #865 
Closes #927
> Whisper updates to allow HF models

- llms/mlx_lm/utils.py
- llms/tests/test_utils.py
- whisper/convert.py
A couple minor fixes here:
- Fix whisper conversion for safetensors models
- Change MLX LM to throw if the save path already exists. This has caused subtle bugs in the past where we overwrite parts of existing models and then end up loading from an invalid model directory. So that is no longer possible (Relevant issue #934)
> Fix whipser conversion for safetensors models

- whisper/README.md
- whisper/mlx_whisper/cli.py
- whisper/mlx_whisper/timing.py
- whisper/mlx_whisper/utils.py
- whisper/mlx_whisper/version.py
- whisper/mlx_whisper/writers.py
- whisper/setup.py
sample:
```
mlx_whisper audio.mp3 \
--model mlx-community/whisper-large-v3-mlx-8bit \
--output_format all \
--word_timestamps True \
--verbose True
```
output files:
```
audio.json
audio.srt
audio.tsv
audio.txt
audio.vtt
```
for more details ues `mlx_whisper --help`
```
mlx_whisper --help
usage: cli.py [-h] [--model MODEL] [--output_dir OUTPUT_DIR] [--output_format {txt,vtt,srt,tsv,json,all}] [--verbose VERBOSE] [--task {transcribe,translate}]
[--language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,yue,zh,Afrikaans,Albanian,Amharic,Arabic,Arm …
```
> Whisper: Support command line

- llms/mlx_lm/models/deepseek.py
- llms/mlx_lm/tuner/utils.py
DeepSeek is still releasing models on their [older MoE architecture](https://huggingface.co/models?other=deepseek).
```sh
mlx_lm.convert --hf-path deepseek-ai/DeepSeek-Prover-V1.5-RL --mlx-path DeepSeek-Prover-V1.5-RL-8bit --q-bits 8 -q
mlx_lm.generate --model DeepSeek-Prover-V1.5-RL-8bit --ignore-chat-template --max-tokens 512 --prompt 'import Mathlib
import Aesop
set_option maxHeartbeats 0
open BigOperators Real Nat Topology Rat
/-- The second and fourth terms of a geometric sequence are $2$ and $6$. Which of the following is a possible first term?
Show that it is $\frac{2\sqrt{3}}{3}$.-/
theorem amc12b_2003_p6 (a r : ℝ) (u : ℕ → ℝ) (h₀ : ∀ k, u k = a * r ^ k) (h₁ : u 1 = 2)
(h₂ : u 3 = 6) : u 0 = 2 / Real.sqrt 3 ∨ u 0 = -(2 / Real.sqrt 3) := by'
```
With MoE:
```sh
mlx_lm.convert …
```
> feat: DeepSeek MoE v1

- llms/mlx_lm/models/phimoe.py
- llms/mlx_lm/models/su_rope.py
- llms/mlx_lm/tuner/utils.py
> Add Phi-3.5-MoE

- llms/mlx_lm/tokenizer_utils.py
Using the `--use-default-chat-template` seems to fail with the new `transformers` library and looking at how we handle `setattr` in the tokenizer wrapper seemed wrong anyway.
New behaviour: any `setattr` call is actually moved to the wrapped tokenizer except if it starts with an underscore.
> Fix `setattr` for the TokenizerWrapper

- llms/mlx_lm/cache_prompt.py
- llms/mlx_lm/generate.py
- llms/mlx_lm/models/base.py
- llms/mlx_lm/utils.py
- llms/setup.py
It adds a command called `mlx_lm.cache_prompt` that processes a prompt and saves the KV cache to a file. It also adds the option to load a KV cache from a file in `mlx_lm.generate`.
Combined with long context models it makes for some awesome applications. The following is an example using it to ask question about MLX to Phi-3.5 .
https://github.com/user-attachments/assets/ad386003-0236-4318-b25d-4fa9d7fa8146
> Add the ability to load the KV cache from a file.

- llms/mlx_lm/cache_prompt.py
This fixes #977 . The result is not going to be identical unfortunately due to the following tokenization artifact.
```python
tokenizer.encode("Hi!")             # [13347, 0]
tokenizer.encode("Hi! What's up?")  # [13347, 0, 3639, 596, 709, 30]
tokenizer.encode("What's up?")      # [3923, 596, 709, 30]
```
> Fix the cache_prompt

- llms/README.md
- llms/mlx_lm/_version.py
- llms/mlx_lm/tokenizer_utils.py
- llms/mlx_lm/utils.py
Since the docs use an instruct model, they should really use a chat template as well to be correct.
Also added a `__call__` overload to `TokenizerWrapper` to appease type-checking.
Closes #972
> Update LLM generation docs to use chat template

- llms/mlx_lm/utils.py
> Don't use private exception class (not in latest huggingface_hub)

- llms/mlx_lm/gguf.py
Fixes #992 .
I think this broke when we moved to nano bind but it is rarely used so it wasn't found out earlier.
> Fix export to gguf

- llms/mlx_lm/SERVER.md
- llms/mlx_lm/server.py
- llms/tests/test_server.py
This pull request introduces a new /v1/models endpoint to mlx_lm.server. The purpose of this addition is to improve compatibility with clients such as Open WebUI, which expect to retrieve a list of available models before use.
Changes:
1. Implemented GET request handling for the /v1/models route
2. Added a method to return information about the loaded model
3. Added tests for the /v1/models route
I've tested Open WebUI compatibility and this now works.
> Add /v1/models endpoint to mlx_lm.server

- llms/mlx_lm/utils.py
- llms/tests/test_generate.py
This update introduces token masking capabilities to the `generate_step` function via a new `logits_processor` parameter. This enhancement supports constrained decoding scenarios that require token masking prior to sampling.
Updates include:
1. New `logits_processor` parameter in `generate_step` function
2. Token masking logic implemented within `_step` function
3. Updated docstring for `generate_step` to describe `logits_processor`
4. Created mx.array of all tokens including prompt
Usage example:
```python
def logits_processor(input_ids: mx.array, logits: mx.array) -> mx.array:
return grammar_processor(input_ids, logits)
```
Here, `grammar_processor` could represent a custom constrained decoding approach.
> Add logits_processor option to generate_step function

- llms/mlx_lm/utils.py
- llms/tests/test_generate.py
Continuation of #983.
This PR refactors the `repetition_penalty` and `logits_bias` logic to utilize the new `logits_processor` argument. These changes:
1. Reduce complexity in the `generate_step` method
2. Modify the `logits_processor` type to accept a list of functions, enabling chained processing
These enhancements allow for more flexible and modular logit processing while simplifying the generation code.
> repetiton_penalty and logits_bias just using logits_processors

- flux/README.md
Small typo fixed in flux README.md that txt2image.py
> Small typo fixed in flux README.md

- llms/mlx_lm/models/plamo.py
The model definition of PLaMo was updated in https://github.com/ml-explore/mlx-examples/pull/603 and it seems to have removed the shared key/value heads so that the output of PLaMo is broken for now.
This PR fixes the issue by reverting the removed part of shared kv heads (as like in llama models)
> Fix PLaMo model to support Grouped Query Attention

- llms/mlx_lm/models/cache.py
- llms/mlx_lm/models/deepseek_v2.py
- llms/mlx_lm/tokenizer_utils.py
- llms/tests/test_tokenizers.py
- Fixes issue with the naive streaming decoder where it would drop tokens when `tokenizer.clean_up_tokenization_spaces` is set.
- Updates BPE matching condition to be more permissive and also mostly fixes it for the case `tokenizer.clean_up_tokenization_spaces`
- Adds some tests
> Tokenizer updates + tests

- llms/mlx_lm/SERVER.md
- llms/mlx_lm/server.py
- llms/tests/test_prompt_cache.py
- llms/tests/test_server.py
Added a basic prompt cache in `mlx_lm.server` for chat mode. But it does support chatting with cache reuse.
> Prompt caching in `mlx_lm.server`

- flux/txt2image.py
Still referring to the sd version of the pipeline class.
> fix: typo on flux model preloading

- llms/mlx_lm/tokenizer_utils.py
I ran into this issue when testing a locally-generated model based on Qwen.
```
----------------------------------------
Exception occurred during processing of request from ('[IP REDACTED]', 32822)
File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
self.process_request(request, client_address)
File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 349, in process_request
self.finish_request(request, client_address)
File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 362, in finish_request …
```
> Handle empty string case in maybe_trim_space

- llms/mlx_lm/convert.py
- llms/mlx_lm/models/gemma2.py
- llms/mlx_lm/utils.py
This change let's you pick the non-quantized weight dtype even when using quantization. There are some models (namely Gemma 2 27B) which can have very large values in the activations that overflow float16.
Also closes #1057
> Override dtype even when quantizing

- clip/eval.py
- clip/linear_probe.py
- clip/requirements.txt
Adds a script to perform linear probe evaluation using the `mlx.data` module for data loading. Mostly a mirror of the [Linear-probe evaluation script from the official CLIP repository](https://github.com/openai/CLIP?tab=readme-ov-file#linear-probe-evaluation).
* https://github.com/ml-explore/mlx-examples/issues/959
> feat(clip): add linear probe evaluation script

- llms/mlx_lm/examples/lora_config.yaml
Fix for #1067:
When updating the config yaml for the addition of full parameter tuning, the `lora_layers` parameter was not adjusted to the new param `num_layers`. In this PR the example lora_config.yaml will be updated with the new param.
> Update lora_config.yaml with new param: num_layers

- llms/mlx_lm/__init__.py
- llms/mlx_lm/tokenizer_utils.py
- llms/tests/test_tokenizers.py
I introduces a bug when trying to port the `clean_up_tokenization_spaces` from HF.
Their match is actually to find and replace instances of ` ' ` with `'`. That one specifically requires a special case to post-process which is tedious, so I just removed that case as I have never seen it come up. But if it does we can revisit.
For reference, the [transformers matching conditions](https://github.com/huggingface/transformers/blob/main/src/transformers/tokenization_utils_base.py#L4052).
Closes #1073
> Fix detokenizer space match for quote

- llms/README.md
- llms/mlx_lm/_version.py
- llms/mlx_lm/chat.py
- llms/mlx_lm/requirements.txt
- llms/mlx_lm/utils.py
Requires [#1510](https://github.com/ml-explore/mlx/pull/1510)
On an M2 Ultra (nothing else needed) the #s for Llama 3.1 70B in 16-bit precision look like:
| | not wired | wired
---  | --- | ---
prompt (16 toks)  | 2.35 toks/sec |  27.8 toks/sec
generation (100 toks) | 0.23 toks/sec | 4.7 toks/sec
Command ran:
```bash
python -m mlx_lm.generate --model meta-llama/Meta-Llama-3-70B-Instruct --prompt "Write a story about Einstein" --max-tokens 100
```
> Wire models in MLX LM

- whisper/convert.py
- whisper/mlx_whisper/_version.py
- whisper/mlx_whisper/decoding.py
- whisper/mlx_whisper/load_models.py
- whisper/mlx_whisper/transcribe.py
- whisper/mlx_whisper/whisper.py
- Allow safetensors as input for faster loading
- Use fewer and more carefully chosen eval
- Precise softmax instead of casting
- Async eval in decode loop
Benchmarks on M2 Ultra
Model | Pre MLX 0.18.0 | Pre MLX Main | Post MLX Main |
--- | ---- | --- | ----
mlx-community/whisper-large-v3-turbo | 16.093 s | 15.642 s | 12.246 s
```python
import time
import mlx_whisper
tic = time.time()
text = mlx_whisper.transcribe("/Users/awnihannun/.cache/whisper/alice.mp3", path_or_hf_repo="mlx_models")["text"]
toc = time.time()
print(f"Time {toc-tic:.3f}")
```
> Whisper improvements

- llms/mlx_lm/generate.py
- llms/mlx_lm/utils.py
As we step the KV cache.. the buffer cache fills up which causes the machine to use more RAM than is really needed.
For example:
```
mlx_lm.generate --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit -m 2048 --prompt - < prompt.txt
```
Pre:
```
Prompt: 32188 tokens, 430.339 tokens-per-sec
Generation: 892 tokens, 32.480 tokens-per-sec
Peak memory: 11.496 GB
Cache memory: 22.795 GB
```
Post:
```
Prompt: 32188 tokens, 424.646 tokens-per-sec
Generation: 892 tokens, 32.211 tokens-per-sec
Peak memory: 11.496 GB
Cache memory: 4.034 GB
```
No difference on M2 Ultra with:
```
mlx_lm.generate --model mlx-community/Mistral-7B-Instruct-v0.3-4bit --prompt "Write a story about Einstein"  --temp 0.0 --max-tokens 512
```
Still hits about 120.5 toks/sec
> Clear cache every now and then

- llms/mlx_lm/tuner/trainer.py
- llms/tests/test_finetune.py
The updates to `LORA.md` are missing but TL;DR we can now do
```
$ echo "m2-ultra-0 slots=1" >>hostfile
$ echo "m2-ultra-1 slots=1" >>hostfile
$ mpirun --hostfile hostfile -- python -m mlx_lm.lora --train --model mlx-community/Mistral-7B-v0.2-4bit --data /path/to/data --batch-size 16
```
to train across two nodes (or more really nothing needs to change).
> Enable distributed LoRA training

- llms/mlx_lm/chat.py
adding max token argument so user can use mlx_lm.chat to generate long reponse
> chore(mlx-lm): add max token arg for mlx_lm.chat

- llms/README.md
- llms/mlx_lm/models/mamba.py
- llms/mlx_lm/utils.py
This PR adds the support of FalconMamba-7B. We add RMS Norms on Mamba B, C and delta parameters when `use_bcdt_rms` is set to `True`. FalconMamba uses non-learnable RMSNorms; However the non-learnable RMS is not supported in mlx. Thus we initialize RMS weights in Mamba forward.  We tried initializing the RMSNorms in the init, with a patch to load them from state dict with dummy weights on the fly, but the generation was two times slower!... The cleanest fix to this would be to add support for non-learnable RMSNorms.
Here is a script to test it
```python
from mlx_lm import load, generate
model, tokenizer = load("tiiuae/falcon-mamba-7b")
response = generate(model, tokenizer, prompt="hello", verbose=True)
```
CC @awni
> Add support for falcon-mamba

- llms/mlx_lm/tokenizer_utils.py
- llms/tests/test_tokenizers.py
Closes https://github.com/ml-explore/mlx-examples/issues/808
> Fix spm decoder multi-byte

- llms/mlx_lm/models/base.py
- llms/mlx_lm/models/cache.py
Currently the rotating KV cache can be both `max_size` and `max_size - 1` depending on whether we filled it by generating or by prompt token processing. This PR makes sure the max is always `max_size ` and not `max_size - 1`.
The following two simple repros exemplify the problem a bit:
```python
from mlx_lm.models.cache import make_prompt_cache
from mlx_lm.utils import load
from mlx_lm.utils import stream_generate
PROMPT = "Tell me a story"
model, tokenizer = load("mlx-community/Llama-3.2-3B-Instruct-4bit")
cache = make_prompt_cache(model, max_kv_size=100)
for text in stream_generate(model, tokenizer, PROMPT, prompt_cache=cache, max_tokens=100):
pass
for text in stream_generate(model, tokenizer, PROMPT, prompt_cache=cache, max_tokens=100):
pass
```
```python
from mlx_lm.models.cache …
```
> Fix rotating kv cache size

- llms/README.md
- llms/mlx_lm/cache_prompt.py
- llms/mlx_lm/chat.py
- llms/mlx_lm/generate.py
- llms/mlx_lm/sample_utils.py
- llms/mlx_lm/server.py
- llms/mlx_lm/tuner/trainer.py
- llms/mlx_lm/utils.py
- llms/tests/test_generate.py
- llms/tests/test_prompt_cache.py
This is part 1 of a potential second part diff to refactor samplers and logits processors outside of the `generate_step` function. The idea being that function is getting too fat.. and it will also be much more flexible to experiment with alternative samplers / logits processors without hacking `generate_step`.
To start this diff:
- Refactors out the sampler and logits processor creation into sampler_utils.py
- Merges the server generation into a single function for stream and completion
- `stream_generate` is more flexible: returns logits and token as well as text and accepts pre-tokenized inputs
- Use wired limit in `stream_generate`
- Use `stream_generate` in the server instead of `generate_step`
- Put generation in a separate stream to avoid breaking async eval when not using the CPU …
> [MLX LM] Sampler refactor + a few improvements

- llms/mlx_lm/utils.py
* Fix missing f-prefix for string interpolation in model size warning
* Ensures proper display of memory values in MB for model and max size
> [MLX LM] Fix f-string formatting in memory warning message

- llms/mlx_lm/generate.py
- llms/mlx_lm/models/hunyuan.py
- llms/mlx_lm/utils.py
- llms/tests/test_models.py
Currently too large to run on in 192GB even in 4-bit. Looking into mixed precision.
> Tencent HunYuan MOE model

- llms/README.md
- llms/mlx_lm/_version.py
- llms/mlx_lm/chat.py
- llms/mlx_lm/examples/chat.py
- llms/mlx_lm/examples/generate_response.py
- llms/mlx_lm/generate.py
- llms/mlx_lm/sample_utils.py
- llms/mlx_lm/server.py
- llms/mlx_lm/tokenizer_utils.py
- llms/mlx_lm/utils.py
- llms/tests/test_generate.py
- llms/tests/test_sample_utils.py
- llms/tests/test_tokenizers.py
- Add a generation response data class for `stream_generate`
- `generate` now uses `stream_generate`
- Server also uses stats recorded by `stream_generate`
- Maybe controversial: I removed the color formatting option. This is broken and there is not a simple fix given that tokens to unicode characters is many-to-many. So we can add it back as a hack which works for most cases or just remove it as I don't think it's used much anymore..
> Generation refactor: part 2

- llms/mlx_lm/SERVER.md
- llms/mlx_lm/server.py
In `mlx_lm.server`'s POST /chat/completions, the "object" property did not match OpenAI's spec.
The value produced was "chat.completions" or "chat.completions.chunk", but should be "chat.completion" or "chat.completion.chunk" for compatibility with clients expecting an OpenAI API.
Refer to:
[The chat completion object](https://platform.openai.com/docs/api-reference/chat/object)
> object string
> The object type, which is always chat.completion.
[The chat completion chunk object](https://platform.openai.com/docs/api-reference/chat/streaming)
> object string
> The object type, which is always chat.completion.chunk.
In particular, this solves a problem for me in which aider 0.64.1 reports hitting a token limit on any chat completion request to mlx_lm.server, no matter how small, despite …
> Fix object property value in mlx_lm.server chat completions response not matching OpenAI spec

- whisper/convert.py
For some reason current implementation logic in the conversion script only allows to use models from predefined list or from huggingface, but when an existing path to a model on a local drive is specified in `--torch-name-or-path` argument, it throws an error.  This error is misleading since it is thrown when a local path actually exists.
> Fix: Allow converting whisper models from local paths

- llms/mlx_lm/utils.py
Improve documentation clarity by:
1. Fix return type annotation to correctly reflect GenerationResponse
2. Simplify docstring by referencing GenerationResponse class
3. Remove redundant field descriptions
> docs: update stream_generate return type annotation

- llms/mlx_lm/utils.py
This change allows mlx_lm.utils.stream_generate to accept an mx.array for its prompt argument
> Accept mx.array type for prompt argument for stream_generate

- flux/flux/sampler.py
According to https://github.com/black-forest-labs/flux/blob/main/demo_gr.py
```python
timesteps = get_schedule(
opts.num_steps,
x.shape[-1] * x.shape[-2] // 4,
shift=(not self.is_schnell),
)
```
and https://github.com/black-forest-labs/flux/blob/main/src/flux/sampling.py
```python
def get_schedule(
num_steps: int,
image_seq_len: int,
base_shift: float = 0.5,
max_shift: float = 1.15,
shift: bool = True,
) -> list[float]:
timesteps = torch.linspace(1, 0, num_steps + 1)
if shift:
mu = get_lin_function(y1=base_shift, y2=max_shift)(image_seq_len)
timesteps = time_shift(mu, 1.0, timesteps)
return timesteps.tolist()
```
and https://github.com/ml-explore/mlx-examples/blob/main/flux/flux/sampler.py
```python
def random_timesteps(self, B, L, dtype=mx.float32, key=None):
if self._schnell:
t = …
```
> Fix bug in FluxSampler.timesteps method

- flux/flux/model.py
Fixes #1116 .
The original checkpoint saved just the transformer model but in the diffusers checkpoint the transformer is nested in the `model` and `diffusion_model`. It seems that the transformer folder would be loadable as is but this small addition to `sanitize()` will work just as well.
> Allow loading from diffusers ckpt

- speechcommands/main.py
Current speechcommands [example](https://github.com/ml-explore/mlx-examples/tree/main/speechcommands#running-the-example) have `nan` value for training loss when iterating from epoch 1 . Looks like there were missing `to_buffer()` sequence in the `data_iter`.
So, we manage to add `to_buffer()` regarding librispeech [config](https://github.com/ml-explore/mlx-data/blob/main/python/mlx/data/datasets/librispeech.py#L134) since we haven't see the actual `to_buffer()` in the `load_speechcommands` [function](https://github.com/ml-explore/mlx-data/blob/main/python/mlx/data/datasets/speechcommands.py#L117-L121)
```bash
(base) ➜  ~ python --version
Python 3.12.4
(base) ➜  ~ python -c "import mlx.core as mx; print(mx.__version__)"
0.20.0
```
```bash
(base) ➜  speechcommands git:(main) ✗ python …
```
> Fix data_iter in prepare_dataset from speechcommands example

- llms/mlx_lm/_version.py
- llms/mlx_lm/cache_prompt.py
- llms/mlx_lm/generate.py
- llms/mlx_lm/utils.py
- llms/tests/test_prompt_cache.py
- Add prompt callback to generate step
- Use the callback in `cache_prompt` (simplifies some code)
- Refactor `generate_step` to accept `max_tokens`.
CC @neilmehta24, the prompt callback takes two arguments (the prompt tokens processed and the total prompt tokens) as it's more flexible. Let me know if that works for you.
> Allow prompt callback to `generate_step`

- llms/mlx_lm/evaluate.py
- llms/setup.py
Add an `mlx_lm.evaluate` CLI that uses [lm-eval](https://github.com/EleutherAI/lm-evaluation-harness) and supports any `mlx-lm` compatible model.
For example:
```
mlx_lm.evaluate --model mlx-community/Qwen2.5-7B-Instruct-4bit --tasks winogrande arc_easy
```
```
Results:
{
"alias": "arc_easy",
"acc,none": 0.8089225589225589,
"acc_stderr,none": 0.008067265958015976,
"acc_norm,none": 0.7975589225589226,
"acc_norm_stderr,none": 0.008245156475629175
}
{
"alias": "winogrande",
"acc,none": 0.6898184688239937,
"acc_stderr,none": 0.0130004541448598
}
```
> `mlx_lm.evaluate`

- llms/mlx_lm/tuner/utils.py
- llms/mlx_lm/utils.py
Support passing a `quant_predicate` callable to `convert` that chooses a custom quantization for each layer in the model.
Example usage in [this gist](https://gist.github.com/barronalex/84addb8078be21969f1690c1454855f3).
Below is a comparison of the average accuracy across 8 `lm-eval` 0-shot reasoning tasks for a variety of our quants.
All experiments were conducted with Qwen2.5-7B-Instruct.
`arc_challenge`, `arc_easy`, `boolq`, `hellaswag`, `openbookqa`, `piqa`, `social_iqa`, `winogrande`
The full benchmarking script is [here](https://gist.github.com/barronalex/0f816636443ca7b6821f31ef488da2a6).
A few thoughts:
- For these tasks, anything from ~5bpw up seems to be around the full fp16 performance
- Mixed quants help, particularly for 3 bit, but you're much better off using n+1 bits with …
> Mixed Quantizations

- flux/flux/flux.py
- flux/flux/sampler.py
Bug can be reproduced when training Flux with batch-size >= 2.
```shell
File "/Volumes/Develop/MLX/mlx-examples/flux/dreambooth.py", line 267, in <module>
loss, grads = step(*batch, guidance, grads, (i + 1) % args.grad_accumulate == 0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Volumes/Develop/MLX/mlx-examples/flux/dreambooth.py", line 238, in step
return single_step(x, t5_feat, clip_feat, guidance), None
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Volumes/Develop/MLX/mlx-examples/flux/dreambooth.py", line 195, in single_step
loss, grads = nn.value_and_grad(flux.flow, flux.training_loss)(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/anaconda3/envs/MLX/lib/python3.12/site-packages/mlx/nn/utils.py", …
```
> Fix shapes mismatch error in FluxPipeline.training_loss when batch-size >= 2

- flux/dreambooth.py
This fixes a crash I spotted at the very end of the `dreambooth.py` example in the `flux` directory.
The code assumed a command line argument was passed in but then always saved to `final_adapters.safetensors`  I think this addresses the issue.
> fix missing --final-adapter-file crash in dreambooth.py

- flux/flux/sampler.py
IMPORTANT!!!
This is a very important and magic value!!!
With the right value 1.15, we can train LoRA very much faster than ever before!!!
See in https://github.com/black-forest-labs/flux/blob/main/src/flux/sampling.py
```python
def get_lin_function(
x1: float = 256, y1: float = 0.5, x2: float = 4096, y2: float = 1.15
) -> Callable[[float], float]:
m = (y2 - y1) / (x2 - x1)
b = y1 - m * x1
return lambda x: m * x + b
def get_schedule(
num_steps: int,
image_seq_len: int,
base_shift: float = 0.5,
max_shift: float = 1.15,
shift: bool = True,
) -> list[float]:
timesteps = torch.linspace(1, 0, num_steps + 1)
if shift:
mu = get_lin_function(y1=base_shift, y2=max_shift)(image_seq_len)
timesteps = time_shift(mu, 1.0, timesteps)
return timesteps.tolist()
```
> Chang Flux's default max_shift to 1.15 to match the official one

- llms/mlx_lm/models/base.py
- llms/mlx_lm/models/cohere2.py
- llms/mlx_lm/tuner/utils.py
- llms/mlx_lm/utils.py
- llms/tests/test_models.py
Adds support for Cohere2 with sliding attention.
Thanks a lot to @N8python for the inspiration!
Bf16
4bit
> Add support for cohere2

- llms/mlx_lm/tokenizer_utils.py
- llms/tests/test_tokenizers.py
This PR fixes the decoding of manually added tokens such as \n in this case. The latter is getting decoded as Ċ.
```
Prompt: Once upon a time in a land far away,
there was a kingdom ruled by a wise and just king. The kingdom was known for its beauty and prosperity, and the people lived in peace and harmony.ĊĊOne day, a terrible drought struck the land, and the crops began to wither and die. The king, worried about the well-being of his people, called upon his wise council to find a solution. The council, after much deliberation, decided to send a group of brave knights to search for a magical spring that was said to have the power to bring rain to the kingdom.
```
```
Prompt: Once upon a time in a land far away,
there was a kingdom ruled by a wise and just king. The kingdom was known for …
```
> Fix decoding manually added tokens

- llms/README.md
- llms/mlx_lm/cache_prompt.py
- llms/mlx_lm/chat.py
- llms/mlx_lm/evaluate.py
- llms/mlx_lm/examples/chat.py
- llms/mlx_lm/examples/generate_response.py
- llms/mlx_lm/generate.py
- llms/mlx_lm/lora.py
- llms/mlx_lm/server.py
- llms/mlx_lm/tuner/datasets.py
- llms/mlx_lm/tuner/trainer.py
- llms/mlx_lm/utils.py
- llms/tests/test_datsets.py
There were a few cases where the way we use chat templates was broken:
For some (but not all) models with a chat template if you apply the chat template without tokenization and then encode to tokens you get duplicate bos tokens. After applying a chat template one should always use `add_special_tokens=False` when encoding to token ids. 
Since we sometimes needs `add_special_tokens=True` (e.g. for base models w/out a chat template) and it's difficult to tell in the general case when we need to add them for a given string prompt, the cleanest solution I found is to just encode prompts to tokens before passing to generate / other places.
Also added a few lines in `stream_generate` to attempt to autodetect the setting of `add_special_tokens` when given a string prompt, but there are edge …
> Fix encoding with special tokens + chat template

- llms/mlx_lm/generate.py
- llms/mlx_lm/tokenizer_utils.py
Currently `--eos-token` is only used if the `eos_token_ids` key is not set in the model config. As a result, most times it is ignored and it can't be used to neither add nor override any eos token.
This PR removes that argument and adds `--extra-eos-token` which allows us to set any number of tokens and token ids in the `eos_token_ids` set. The only behavior that is changed is for the generate script.
> Change the eos-token argument for `mlx_lm.generate`

- llms/mlx_lm/utils.py
There are in my opinion two reasons to use `upload_large_folder` instead of `upload_folder`:
- The `multi_commits` args are no longer supported by `upload_folder`. Attempting to convert and upload a model with a recent version of `huggingface_hub` will fail. This includes a new install of `mlx-lm` in an empty environment.
- `upload_large_folder` is more efficient and resilient than `upload_folder`. There are also [some limitations](https://huggingface.co/docs/huggingface_hub/v0.27.1/en/package_reference/hf_api#huggingface_hub.HfApi.upload_large_folder), but I think they don't apply here.
> Use upload_large_folder

- llms/mlx_lm/lora.py
currently, cli arg defaults overwrite lora config yaml
```bash
cat config.yaml | grep fine_tune_type
fine_tune_type: full
mlx_lm.lora --config config.yaml
...
cat adapters/adapter_config.json | grep fine_tune_type
"fine_tune_type": "lora",
```
setting the cli arg overwrites the config yaml as expected but should not be necessary
```bash
cat config.yaml | grep fine_tune_type
fine_tune_type: full
mlx_lm.lora --config config.yaml --fine-tune-type full
...
cat adapters/adapter_config.json | grep fine_tune_type
"fine_tune_type": "full",
```
after these changes the config yaml can be used as expected
```bash
cat config.yaml | grep fine_tune_type
fine_tune_type: full
mlx_lm.lora --config config.yaml
...
cat adapters/adapter_config.json | grep fine_tune_type
"fine_tune_type": "full",
```
cli arg …
> fix(lora): config yaml & arg default merge bug

- llms/mlx_lm/_version.py
- llms/mlx_lm/examples/pipeline_generate.py
- llms/mlx_lm/models/deepseek_v3.py
- llms/mlx_lm/requirements.txt
- llms/mlx_lm/utils.py
- llms/tests/test_models.py
- llms/tests/test_utils_load_model.py
Run with the script `examples/pipeline_generate.py`:
Requires building MLX from source on main.
Set wired sysctl to at least 170000:
```
sudo sysctl iogpu.wired_limit_mb=170000
```
Install Open MPI and Make a host file `hosts.txt` with the appropriate values. More info [here](https://ml-explore.github.io/mlx/build/html/usage/distributed.html#).
Change paths below and run with:
```
/Users/awnihannun/miniconda3/bin/mpirun -np 2 --hostfile ~/hosts.txt python /Users/awnihannun/mlx-examples/llms/mlx_lm/examples/pipeline_generate.py
```
The first time you run it will download the full 3-bit model on each machine which can take a while. Would be a nice optimization to only download the weights that are needed by each process.
> deepseek v3 model with pipeline parallelism

- llms/mlx_lm/generate.py
- llms/mlx_lm/utils.py
Benchmarks on M3 Max:
Baseline:
```bash
mlx_lm.generate --model mlx-community/Qwen2.5-32B-Instruct-4bit --prompt "Write a quick sort in C++" -m 256
```
Prompt: 36 tokens, 86.936 tokens-per-sec
Generation: 256 tokens, 19.680 tokens-per-sec
Peak memory: 18.573 GB
With speculative decoding:
```
mlx_lm.generate --model mlx-community/Qwen2.5-32B-Instruct-4bit --prompt "Write a quick sort in C++" -m 256 --draft-model mlx-community/Qwen2.5-0.5B-Instruct-8bit --num-draft-tokens 4
```
Prompt: 36 tokens, 87.853 tokens-per-sec
Generation: 256 tokens, 35.738 tokens-per-sec
Peak memory: 19.112 GB
The outputs are identical.
A note on the implementation.. it seemed simpler to start to have a separate `speculative_generate_step` rather than try to merge everything. I might refactor a bit so they can use …
> Add a speculative decoding generator

- llms/mlx_lm/models/base.py
- llms/mlx_lm/models/cohere2.py
PR #1173 introduced a shape mismatch error in the Cohere2 attention mask when processing contexts larger than 4K tokens. The issue stems from incorrect cache indexing in the attention mask creation.
Reported [here](https://x.com/ivanmeallares/status/1878140524093125076).
The `create_attention_mask` function was using a hardcoded index (`cache[0]`) to access cache information, instead of using the appropriate layer-specific index. This caused incorrect offset calculations for sliding window patterns in deeper layers.
- Added `layer_idx` parameter to `create_attention_mask` with default value 0.
- Modified cache access to use `cache[layer_idx]` instead of `cache[0]`
- Updated Cohere2 model to pass the correct layer index based on sliding window pattern
Tested with context length of 16,539 …
> Fix Cohere2: mask shape error (long context)

- llms/mlx_lm/LORA.md
- llms/mlx_lm/lora.py
- llms/mlx_lm/tuner/datasets.py
Building on #996, generalize `prompt_feature` and `completion_feature` parameters used with HF datasets for local datasets to facilitate compatibility with training dataset formats of many other systems (Alpaca, for example):
```yaml
data = "/path/to/file.jsonl"
prompt_feature: "input"
completion_feature: "output"
```
> Custom local dataset features

- llms/mlx_lm/tuner/trainer.py
- llms/tests/test_finetune.py
Workaround for #1185 in case of distributed training, as suggested by @awni
> reduction moved to CPU in case of distributed training

- llms/mlx_lm/lora.py
sorry! i did not test https://github.com/ml-explore/mlx-examples/pull/1196 well enough and caused an issue when trying to clean up default args
currently cli args with `action="store_true"` are not overwritten by config yaml because they are set to `False` instead of `None`
https://github.com/ml-explore/mlx-examples/blob/c117af83b8cbec15523bd0d69e7a57f01237ca89/llms/mlx_lm/lora.py#L289-L291
this results in needing to set `--train`, `--test`, and `--grad-checkpoint` via cli as config yaml is not respected
setting `default=None` on these args fixes the issue
> fix(lora): add back store_true default args

- llms/mlx_lm/tuner/datasets.py
Fixes the error `NameError: name 'train_ds' is not defined`, which is currently thrown when using a configuration like this for the LORA tuner:
```yml
hf_dataset:
name: "OpenAssistant/oasst_top1_2023-08-25"
train_split: "train"
valid_split: "test"
text_feature: "text"
```
> Fix dataset variable name, in `datasets.py`

- llms/mlx_lm/examples/pipeline_generate.py
- llms/mlx_lm/models/deepseek_v3.py
- Use `stream=mx.cpu` during prompt processing otherwise the gpu sometimes times out
- Allow model to be an argument in the `pipeline_generate.py` script.
> Some fixes for pipeline parallel deep seek r1

- ACKNOWLEDGMENTS.md
- llms/mlx_lm/models/helium.py
- llms/mlx_lm/tuner/utils.py
I use the origional helium 2b model from [kyutai/helium-1-preview-2b](https://huggingface.co/kyutai/helium-1-preview-2b) - `kyutai/helium-1-preview-2b`.
`python -m mlx_lm.generate --model kyutai/helium-1-preview-2b --prompt "This is the test to" -m 12`
output:
```text
Fetching 5 files: 100%|█████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 64927.31it/s]
==========
see also known as the 190190
==========
Prompt: 6 tokens, 22.699 tokens-per-sec
Generation: 12 tokens, 5.039 tokens-per-sec
Peak memory: 5.526 GB
```
---
```text
python -m mlx_lm.lora \
--model kyutai/helium-1-preview-2b \
--train \
--data /Users/gokdenizgulmez/Library/Mobile\ Documents/com\~apple\~CloudDocs/Datastes/data_smoll \
--iters 100 \
--batch-size 1 \
--num-layers 8 \ …
```
> adding support for kyutai's helium

- llms/mlx_lm/server.py
- llms/tests/test_server.py
In the latest version of SmolAgents, it has started using message content fragments formatted as `content = { type: 'text', content: 'hello world' }` instead of using a string for the text content. This change breaks compatibility with the mlx-lm.server. To make the mlx-lm server compatible with this new format,  added to convert content from text fragments to text strings in order to apply chat template.
After fixing, we can use mlx-lm.server with smolagents as shown below:
```py
from smolagents import CodeAgent, OpenAIServerModel
model = OpenAIServerModel(
api_base="http://<your-mlx-server>:8080",
api_key="n/a",
model_id="default_model",
temperature=0,
max_tokens=8000,
)
agent = CodeAgent(tools=[], model=model, add_base_tools=True)
agent.run(
"How many seconds would it take for a …
```
> chore(mlx-lm): support text type content in messages

- llms/mlx_lm/models/helium.py
- llms/mlx_lm/models/mamba.py
- llms/mlx_lm/models/minicpm.py
This PR optimizes the MambaBlock implementation to improve performance and cache handling while maintaining compatibility with the existing MambaCache interface.
1. **Batched Input Processing**
- Processes all tokens simultaneously through `in_proj` instead of one at a time
- Reduces number of operations and improves parallelization
- Uses reshape to maintain batch dimensions efficiently
2. **Refactored Core Logic**
- Introduced `_process_sequence` method to separate main processing logic from cache handling
- Improves code maintainability and makes future optimizations easier
- Clearer separation between state management and computation
3. **Enhanced Cache Handling**
- Added robust type checking for different cache formats
- Maintains backwards compatibility with list-based caches
- …
> Optimizations for mamba1

- llms/mlx_lm/models/deepseek_v2.py
- llms/mlx_lm/models/deepseek_v3.py
Uses put along axis directly (simpler) and compiles for v3. For R1 it's between 0.5-1 tok/sec.
> Faster DSv2/3 expert score computation

- whisper/mlx_whisper/timing.py
- whisper/mlx_whisper/whisper.py
- Don't upcast qk scores until needed
- Don't store alignment head info as mx.array since we only use it as if it were a list (all the `.item` are causing lots of graph evals)
- Use precise softmax
Speedup is pretty small but also good to demonstrate correct usage.
> Some improvements to speedup alignment computation in MLX Whisper

- llms/mlx_lm/examples/chat.py
Currently, the `temp` argument [here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/examples/chat.py#L26) causes the `generate()` to fail with the following error:
`TypeError: generate_step() got an unexpected keyword argument 'temp'`
Removal of this deprecated argument fixes it. 
cc @awni
> Remove temp argument

- llms/mlx_lm/LORA.md
- llms/mlx_lm/lora.py
- llms/mlx_lm/tokenizer_utils.py
- llms/mlx_lm/tuner/datasets.py
- llms/mlx_lm/tuner/trainer.py
- llms/tests/test_datsets.py
PR Merge of #825, #1090 and fix for #1095 due to combined benefit for use in fine-tuning instruction models with HF completion datasets
> Completion only fine-tuning of instruction models with collections of HF datasets

- llms/mlx_lm/models/deepseek_v2.py
- llms/mlx_lm/models/deepseek_v3.py
It was possible for the last rank to get 0 / a pretty uneven number of layers before.
For example for 60 layers with 31 machines.
> Fix sharding for more even number of layers

- llms/mlx_lm/utils.py
> Add logits processor to spec gen

- clip/convert.py
I updated the `torch.load` function in `convert.py` to explicitly set `weights_only=True`.
This change prevents the FutureWarning
```bash
FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via …
```
> Fix FutureWarning in torch.load by setting weights_only=True

- llms/mlx_lm/evaluate.py
- Better default limit in evaluation
- Check if max tokens are in generation options
Closes #1288
> Use max tokens from options in mlx_lm evaluate

- llms/mlx_lm/_version.py
- llms/mlx_lm/chat.py
- llms/mlx_lm/models/deepseek_v3.py
- llms/mlx_lm/utils.py
Support the new Kimi MOE model (it's model type is `deepseek_v3` but it uses regular RoPE).
Some QOL updates to `mlx_lm.chat` to allow reset and print help.
> support kimi + more options in chat mode

- lora/lora.py
Fixes issue where nohup.out only shows logs after script completion, making real-time monitoring impossible. Detects Python version and applies appropriate buffering fix.
> chore(lora): Add real-time log buffering fix for nohup execution

- llms/mlx_lm/generate.py
- llms/mlx_lm/models/base.py
This let's us route to SDPA for some cases where it is supported especially after https://github.com/ml-explore/mlx/pull/1922 lands.
This + 1922 speeds things up with speculative decoding. Benchmarks on M4 Max:
```
mlx_lm.generate --model mlx-community/Qwen2.5-32B-Instruct-4bit --draft-model mlx-community/Qwen2.5-0.5B-Instruct-4bit --prompt "Write a very long quick sort in C++ followed by a very long merge sort. Then do the same in Python." -m 4096 --num-draft-tokens 3
```
Pre: Generation: 1172 tokens, 37.347 tokens-per-sec
Post: Generation: 1172 tokens, 41.503 tokens-per-sec
And for a much longer prompt:
Pre:
```
Prompt: 35371 tokens, 123.414 tokens-per-sec
Generation: 512 tokens, 6.749 tokens-per-sec
Peak memory: 33.348 GB
```
Post:
```
Prompt: 35371 tokens, 127.796 tokens-per-sec …
```
> Use a bool mask for attention

- llms/mlx_lm/examples/tool_use.py
An example showing how to use MLX LM with Qwen 2.5 for tool use.
```
==========
<tool_call>
{"name": "multiply", "arguments": {"a": 12234585, "b": 48838483920}}
</tool_call>
==========
Prompt: 221 tokens, 201.048 tokens-per-sec
Generation: 42 tokens, 25.755 tokens-per-sec
Peak memory: 18.839 GB
==========
The product of 12234585 and 48838483920 is 597518582790373200.
==========
Prompt: 56 tokens, 163.097 tokens-per-sec
Generation: 47 tokens, 25.539 tokens-per-sec
Peak memory: 18.839 GB
```
> Tool use example

- cifar/README.md
- cifar/dataset.py
- cifar/main.py
I am not sure if it ended up being a bit verbose and out of scope. Perhaps it makes sense to have more dedicated DDP training examples.
It also only works on master as I am using `mx.distributed.all_sum(scalar)`
> Distributed support cifar

- llms/mlx_lm/examples/lora_config.yaml
- llms/mlx_lm/lora.py
Added ability to select between Adam, AdamW, and Muon optimizers with customizable parameters via command-line or YAML config. This gives users more flexibility to optimize their fine-tuning process for different models and datasets.
> Adding multiple optimizers to mlx lm

- llms/tests/test_prompt_cache.py
I think it's just a tolerance issue since we changed the quantization in 0.23.2
> fix flaky test

- llms/mlx_lm/chat.py
- llms/mlx_lm/generate.py
This PR implements the suggestion from issue #1318 to change the default seed behavior for text generation.
- Changed `DEFAULT_SEED` from `0` to `None` in both `generate.py` and `chat.py`
- Modified the main functions to only set the seed when explicitly provided
- Updated help text to clarify the new default behavior
As described in issue #1318:
> The mlx_lm scripts (chat.py and generate.py) currently enforce a fixed default seed of 0 for text generation, resulting in identical outputs across runs even when using stochastic sampling (e.g., --temp 1). This behavior stems from an explicit call to mx.random.seed(0) in both scripts, overriding the natural time-based RNG provided by MLX's core library in mlx.core.random.
> 
> While this ensures reproducibility, it contrasts with the typical …
> Change DEFAULT_SEED to None for stochastic generation by default

- llms/mlx_lm/models/llama.py
Remove the LM head in llama models if unused so weight validation doesn't fail.
Closes https://huggingface.co/spaces/mlx-community/mlx-my-repo/discussions/36
> Remove lm head if unused

- llms/mlx_lm/convert.py
The argument was broken because of the string value, but not using the string value causes a name clash. Using a simpler approach here.
> Fix mixed quant option

- llms/mlx_lm/sample_utils.py
- llms/tests/test_sample_utils.py
Closes #1219 
Apply samplers in this order: top-k --> top-p --> min-p --> temp
The sampler methods were refactored to return the transformed logits instead of a token. Now, we can can chain them together to apply a series of sampling methods.
The method names of the samplers were changed to indicate that the implementation has changed, i.e., each method returns logits instead of a token. I am not sure about the API stability requirements, so let me know if you have a preference on the method name.
The temperature adjustment was removed from each sampler application, and instead it's applied only once as the very last step.
> `make_sampler` creates sampler chain with all sampling parameters

- llms/mlx_lm/tokenizer_utils.py
Explicitly set the `encoding` to UTF-8 when loading `tokenizers.json`, because as the documentation for [open()](https://docs.python.org/3/library/functions.html#open) says
> if encoding is not specified the encoding used is platform-dependent
which resulted in the following error when running in an (admittedly unusual) environment with no locale set
```
Python exception: 'ascii' codec can't decode byte 0xc2 in position 6725: ordinal not in range(128)
Traceback:
File "test.py", line 36, in load_model
model, tokenizer = mlx_lm.load(name)
~~~~~~~~~~~^^^^^^
File "venv/lib/python3.13/site-packages/mlx_lm/utils.py", line 788, in load
tokenizer = load_tokenizer(
model_path, tokenizer_config, eos_token_ids=config.get("eos_token_id", None)
)
File …
```
> Make sure to use UTF-8 when loading tokenizer.json

- lora/README.md
--hf-repo is not part of `fuse.py` arguments
> LoRa/README.md should be --hf-path instead of --hf-repo

- whisper/mlx_whisper/cli.py
There were several mentions of `--word-timestamps` option as `--word_timestamps`and another one using underscores not matching the actual option.
> Update cli.py command help text lines mentioning --word-timestamps
