mistral/requirements.txt

Add missing numpy dependency

---

transformer_lm/main.py

Fix: transformer_lm bug in eval_fn

---

stable_diffusion/requirements.txt

fix(sd): Add mlx as a dependency

---

llama/README.md

Hi there,
Thanks a ton for open-sourcing such a brilliant library for faster and better inference on Mac devices!
In order to make it easy for developers to access mlx converted llama checkpoints, we've uploaded the most commonly used checkpoints (7B) and uploaded them to the Hugging Face Hub - https://huggingface.co/mlx-llama. 
Thanks again for your brilliant work!

Add url to (llama) mlx checkpoints on HF.

---

llama/README.md
llama/convert.py

Fix/ workaround to error:
```
TypeError: Got unsupported ScalarType BFloat16
```

Fix unsupported ScalarType BFloat16

---

whisper/README.md
whisper/requirements.txt

Update whisper readme + requirements

---

stable_diffusion/README.md

replaced 'Hugginface' with 'Huggingface'

fix typo in README.md

---

llama/README.md

Thanks for this project, a minor documentation change i propose after installing the project and giving a shot to some examples. The llama python instruction was unclear. I propose to put a 'path', just like for the tokenizer on the same command line.

📝 Clarify python command for llama example

---

README.md

updates readme with recently added examples: Mixtral, BERT, GCN

Update README.md with recently added examples

---

whisper/benchmark.py
whisper/test.py
whisper/whisper/decoding.py
whisper/whisper/load_models.py
whisper/whisper/transcribe.py
whisper/whisper/whisper.py

Enable FP16 for Whisper and make it the default (following the original implementation).

Enable FP16 for Whisper

---

bert/hf_model.py
llama/README.md
llama/convert.py
llama/llama.py
llama/requirements.txt
mixtral/README.md
stable_diffusion/README.md
stable_diffusion/stable_diffusion/model_io.py
stable_diffusion/stable_diffusion/tokenizer.py

Enable support for llama v2 and larger llama models with sharded weights to address #56 
I am moving this example to be more like the `mistral` / `mixtral` example just for the sake of consistency. Still keeping the nicely commented generation loop since that's pretty useful IMO.

llama v2 with sharded weights

---

whisper/whisper/whisper.py

Hi @awni,
Thanks for working on enabling fp16 for the whisper model! However, the inference still fails with the following error:
```
File "/Users/bofenghuang/Projects/mlx-examples/whisper/tmp.py", line 5, in <module>
result = whisper.transcribe(
File "/Users/bofenghuang/Projects/mlx-examples/whisper/whisper/transcribe.py", line 244, in transcribe
result: DecodingResult = decode_with_fallback(mel_segment)
File "/Users/bofenghuang/Projects/mlx-examples/whisper/whisper/transcribe.py", line 176, in decode_with_fallback
decode_result = model.decode(segment, options)
File "/Users/bofenghuang/Projects/mlx-examples/whisper/whisper/decoding.py", line 724, in decode
result = DecodingTask(model, options).run(mel)
File …
```

Fix whisper fp16 inference

---

mixtral/README.md

Trying to help folks out who miss the need to specifically call git-lfs

Update README.md to fix git-lfs command

---

llama/llama.py
mixtral/README.md
mixtral/convert.py
mixtral/mixtral.py
mixtral/params.json
phi2/convert.py
whisper/test.py
whisper/whisper/decoding.py
whisper/whisper/load_models.py
whisper/whisper/transcribe.py
whisper/whisper/whisper.py

- Use the official Mixtral Hugging Face repo
- Weight conversion is now streaming so it uses quite a bit less RAM in total (~30GB instead of 100+)
Issue #92 and #81

Use official HF for mixtral

---

mixtral/mixtral.py

- Set RoPE base correctly
- Default temp to 0 as it seems to work better
- Following [reference](https://github.com/mistralai/mistral-src/blob/main/moe_one_file_ref.py) upcast gate scores prior to softmax
#100

[Bugfix] Fix RoPE base bug in Mixtral example

---

llama/README.md
llama/llama.py
phi2/phi2.py

Use the same derived RoPE as Mixtral until we release the updates in `mlx.nn`.

Rope theta to support Coda Llama

---

llama/README.md
llama/convert.py
llama/llama.py

H/T  @andersonbcdefg in #65 who put up a preliminary version of the conversion script!

Support for tiny llama in llama example

---

llama/llama.py

fix renamed arg

---

ACKNOWLEDGMENTS.md
README.md

Citation + contributor acknowledgments section

---

lora/convert.py
lora/lora.py

As per title, just a couple minor fixes.
Fixes: https://github.com/ml-explore/mlx/issues/213

Fix Lora with llama 2 from meta

---

mixtral/convert.py
mixtral/mixtral.py

Similar to https://github.com/ml-explore/mlx-examples/pull/157

Add config.json to Mixtral.

---

llms/mistral/convert.py
llms/mistral/mistral.py
llms/mixtral/README.md
llms/mixtral/convert.py
llms/mixtral/mixtral.py

use same argument convention for mistral/mixtral as for llama convert.

rename --model_path to --model-path

---

speechcommands/README.md

Updated results after training `kwt1` and `kwt2` for 100 epochs.

updated speech commands results

---

mnist/README.md
mnist/jax_main.py
mnist/main.py
mnist/mnist.py
mnist/torch_main.py

fashion-mnist example

---

mnist/README.md

fixed typo JAX (Just After eXecution)

updated README

---

llms/llama/llama.py

Corrected the return signature of __call__ method in Attention Module in llama.py

Fixed the return type for the __call__ method in Attention

---

llms/llama/convert.py

keep dtype on model conversion

---

llms/hf_llm/generate.py

Fix hf_llm to use actual prompt

---

llms/hf_llm/convert.py

- will be much faster
h/t @angeloskath for pointing this out

Force fp16 for non-quantized weights in quantized models

---

lora/convert.py
lora/lora.py

Forgot to remove this when we added transposed quantize kernels.

Quantize linear layer in LoRA

---

whisper/convert.py
whisper/requirements.txt

[Whisper] Add HF Hub upload option.

---

whisper/whisper/load_models.py
whisper/whisper/transcribe.py

[Whisper] Add load from Hub.

---

stable_diffusion/txt2image.py

Fix image conversion in txt2image

---

lora/lora.py

[Lora] Fix max tokens argument

---

lora/README.md
lora/lora.py
whisper/README.md
whisper/test.py
whisper/whisper/transcribe.py

Closes #280 and #281
I'm piggybacking some updates to the whisper example on this as well:
- fix test
- better default model
- Updates to README

[Lora] Fix generate

---

llms/hf_llm/convert.py

I haven't tested it locally, I just quickly looked at the code. It seems that after introducing the local flag, hf_path becomes undefined.

fix(hf_llm): undefined hf_path

---

speechcommands/README.md
speechcommands/requirements.txt
whisper/README.md

Use pip for mlx data with speech commands

---

lora/README.md
lora/convert.py
lora/fuse.py
lora/lora.py
lora/models/base.py
lora/models/llama.py
lora/models/lora.py
lora/models/phi2.py
lora/utils.py
stable_diffusion/txt2image.py
whisper/whisper/load_models.py

- Changed architecture of lora directory to match hf_llm
- Added lora finetune support for Phi-2 model

Added lora support for Phi-2

---

llms/README.md
llms/mlx_lm/models/phi2.py

Just quickly update the model args to match config.json in Phi2's official HF repository configuration.

chore(mlx-lm): update phi2 model args to sync with hf config format.

---

llms/mlx_lm/utils.py
llms/setup.py

Fix response of LLM generate API.

Fix response + bump version

---

mnist/main.py
stable_diffusion/stable_diffusion/__init__.py

- `mx.maximum(x, 0.0)` -> `nn.relu(x)`
- `mx.mean(cross_entropy(x, y))` -> `cross_entropy(x, y, reduction="mean")`
- `mx.minimum(1, mx.maximum(0, x))` -> `mx.clip(x, 0, 1)`

Refactor activation function and loss calculation

---

llms/mlx_lm/models/llama.py
llms/mlx_lm/utils.py
stable_diffusion/image2image.py

Two minor fixes (loading weights for large llamas, and stable diffusion im2im)

---

llms/llama/llama.py
llms/llama/requirements.txt

This example requires pandas. Also added eos param that would stop generating the text if EOS token generated.

Missing requirements needed for convert script

---

llms/mlx_lm/convert.py
llms/mlx_lm/utils.py

Fix for: https://github.com/ml-explore/mlx-examples/issues/305

chore: fix the convert.py script for weights are not sanitized and support quant for non-32 dimensions

---

lora/convert.py
lora/fuse.py
lora/lora.py
lora/models.py
lora/models/mixtral.py
lora/utils.py

Quick and dirty implementation to support Mixtral while still work in progress on moving Lora to mlx-lm.
Close https://github.com/ml-explore/mlx-examples/issues/323

chore(lora): support mixtral in lora example

---

llms/README.md

Add conda installation option to the docs of `mlx-ml`.

Update docs with `conda` install option

---

llms/mlx_lm/generate.py
llms/mlx_lm/utils.py

It's the same fix as PR #321 as it fixed the code in utils.py, but the function generation is not used in main function.
So I do it once again here.

fix the chinese character generation as same as PR #321

---

llms/mlx_lm/utils.py

Close https://github.com/ml-explore/mlx-examples/issues/367
cc @awni

fix(mlx-lm): handle legacy quant models

---

llms/mlx_lm/lora.py
llms/mlx_lm/tuner/lora.py
llms/mlx_lm/utils.py

Add LoRA hyperparameters based on the https://github.com/microsoft/LoRA/blob/main/loralib/layers.py with slight modifications to support advanced LoRA fine-tuning.

feat(mlx-lm): add lora hypeparameters in lora layer

---

llms/mlx_lm/fuse.py
llms/mlx_lm/tuner/lora.py
llms/mlx_lm/tuner/utils.py
llms/mlx_lm/utils.py

Add de-quant support for mlx-lm fuse.py, manually tested locally.

feat(mlx-lm): add de-quant for fuse.py

---

llms/llama/convert.py
llms/mlx_lm/utils.py
lora/utils.py
stable_diffusion/image2image.py
stable_diffusion/txt2image.py
transformer_lm/main.py

After compile lands we will no longer support simplify, so this PR removes it.

remove simplify

---

stable_diffusion/README.md
stable_diffusion/requirements.txt
stable_diffusion/stable_diffusion/__init__.py
whisper/requirements.txt
whisper/test.py
whisper/whisper/decoding.py

MLX switches to use tuple for shape in Python in https://github.com/ml-explore/mlx/pull/591
I ran every example and I only found 2 which had issues: stable_diffusion and whisper. Also I really appreciated how easy our examples are to run in the process 😄 .

Work with tuple shapes

---

llms/mlx_lm/lora.py
llms/mlx_lm/models/olmo.py
llms/mlx_lm/utils.py
llms/setup.py

Simple PR just adds an Olmo model class to run the new Allen AI model.
Using the safetensors version, model works:
```shell
python -m mlx_lm.generate --model saurabh-shah/olmo-7b-safetensors --prompt "Write a quick sort in C++" 
Fetching 14 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 36815.21it/s]
==========
Prompt: Write a quick sort in C++
.
Write a quick sort in C++.
- You must use a C++ compiler to complete this assignment.
- You may not use any additional libraries.
- You must use C++11.
- Your sort must be a stable sort (i.e., it returns the same order for the same inputs
across runs).
- Your sort must be in-place.
Submit your code as a
==========
Prompt: 9.931 tokens-per-sec
Generation: 20.045 …
```

Olmo in MLX LM

---

llms/mlx_lm/models/olmo.py

@awni While quantizing the Olmo 1B model, I just noticed that there are some bugs in the current implementation.

fix(mlx-lm): olmo 1b model

---

llms/mlx_lm/models/olmo.py

fix the issue for https://github.com/ml-explore/mlx-examples/issues/423

fix(mlx-m): lazy load hf_olmo

---

transformer_lm/main.py

loss_fn(), originally loss(), was extracted from the Transformer class. References to the original loss function were not updated.

Clean up loss function extraction

---

llms/mlx_lm/tuner/trainer.py
llms/mlx_lm/tuner/utils.py
llms/setup.py

This commit enhances the error handling when the specified LoRA layer count exceeds the total number of layers in the model. It clarifies the error message to provide actionable feedback for users, guiding them to adjust their input parameters accordingly.

LoRA: Improve validation error for LoRA layer count exceeding model layer

---

llms/mlx_lm/models/qwen2.py
llms/setup.py
stable_diffusion/stable_diffusion/__init__.py

Fix Qwen2 and SD

---

llms/gguf_llm/models.py
llms/mistral/mistral.py
llms/mixtral/mixtral.py
llms/mlx_lm/models/llama.py
llms/mlx_lm/models/mixtral.py
llms/mlx_lm/models/phi.py
llms/mlx_lm/models/qwen2.py
llms/mlx_lm/models/stablelm_epoch.py

Simplify repeat and provide ~1.5 tps for quantized mistral 7B.

Change gqa to use repeat instead of concatenate

---

.circleci/config.yml
llms/mlx_lm/tuner/trainer.py

Add basic style checks to MLX examples

Basic CircleCI

---

llms/mlx_lm/models/gemma.py
llms/mlx_lm/requirements.txt
llms/mlx_lm/tuner/trainer.py
llms/mlx_lm/tuner/utils.py

Add support for gemma model type:
Should run with:
python -m mlx_lm.generate --model google/gemma-7b-it --prompt "Write a quick sort in C++"

Gemma support

---

llms/mlx_lm/__init__.py
llms/setup.py

[mlx-lm] bump version and include in package

---

llms/mlx_lm/server.py

Partially resolve https://github.com/ml-explore/mlx-examples/issues/478.

chore: add /v1/completions for server.py

---

llms/mlx_lm/SERVER.md
llms/mlx_lm/server.py

Address the comment from https://github.com/ml-explore/mlx-examples/pull/486

chore(mlx-lm): refactor server.py to utilize generate_step from utils for consistency

---

llms/mlx_lm/LORA.md
llms/mlx_lm/generate.py
llms/mlx_lm/lora.py

close https://github.com/ml-explore/mlx-examples/issues/488

chore(mlx-lm): add adapter support in generate.py

---

CONTRIBUTING.md
llms/CONTRIBUTING.md
llms/mlx_lm/models/starcoder2.py

Add small section based on learnings

Add tips on porting LLMs from HuggingFace

---

llms/mlx_lm/models/qwen2.py

fix https://github.com/ml-explore/mlx-examples/issues/543

chore(mlx-lm): enable tie_word_embeddings config for qwen2

---

.circleci/config.yml
llms/CONTRIBUTING.md
llms/mlx_lm/models/gemma.py
llms/mlx_lm/models/mixtral.py
llms/mlx_lm/models/olmo.py
llms/mlx_lm/models/phi.py
llms/mlx_lm/models/plamo.py
llms/mlx_lm/models/qwen.py
llms/mlx_lm/models/stablelm.py
llms/mlx_lm/models/starcoder2.py
llms/tests/test_models.py
llms/tests/test_utils.py

- I think it's time to start testing MLX LM since it's gotten a bit big and manual testing is tedious.
- Added the tests to run in Circle as well.

Enable unit testing in Circle and start some MLX LM tests

---

llms/mlx_lm/tuner/lora.py

As title. I think it's a more reasonable default. Also a temporary patch for https://github.com/ml-explore/mlx/issues/810

Dropout 0 as default for LoRA

---

stable_diffusion/stable_diffusion/__init__.py
stable_diffusion/txt2image.py

allowing `seed=0` to be passed and adding `--seed` to txt2image.

feat: stable-diffusion t2i add --seed

---

llms/mlx_lm/models/llama.py
llms/mlx_lm/models/qwen2.py
llms/mlx_lm/models/starcoder2.py
llms/mlx_lm/utils.py
llms/tests/test_models.py

fix: https://github.com/ml-explore/mlx-examples/issues/564

chore(mlx-lm): fix tie_word_embeddings for qwen2

---

llms/mlx_lm/tuner/trainer.py

Add peak_memory info to training callback

---

llms/mlx_lm/server.py

Add --trust-remote-code to server

Update server.py to add --trust-remote-code to server

---

stable_diffusion/image2image.py
stable_diffusion/requirements.txt
stable_diffusion/txt2image.py

Fix requirements and image2image strength/steps mismatch

---

llms/mlx_lm/LORA.md
llms/mlx_lm/lora.py
llms/mlx_lm/models/mixtral.py
llms/mlx_lm/models/phi.py
llms/mlx_lm/models/phixtral.py
llms/mlx_lm/utils.py

- Use SDPA for Mixtral
- Use no repeat for phi
- Store keys in fp16 for phi, phixtral
Also closes #526

Make attention faster for a some models

---

llms/mlx_lm/lora.py
llms/tests/test_lora.py

address https://huggingface.co/mlx-community/Mixtral-8x7B-Instruct-v0.1-hf-4bit-mlx/discussions/1

chore(mlx-lm): fix print_trainable_parameters for quant models

---

llms/mlx_lm/LORA.md
llms/mlx_lm/fuse.py
llms/mlx_lm/gguf.py
llms/mlx_lm/version.py

feat(mlx-lm): export the GGUF (fp16) format model weights from fuse.py

---

llms/mlx_lm/tuner/trainer.py

address https://github.com/ml-explore/mlx-examples/issues/607
Please feel free to close this PR if it doesn't fit the purpose.

chore(mlx-lm): fix lora for moe model

---

llms/mlx_lm/utils.py
whisper/convert.py
whisper/test.py
whisper/whisper/audio.py
whisper/whisper/transcribe.py
whisper/whisper/whisper.py

- Some minor nits in whisper + fix failing test
- Fix #637 to not crash when no tokens are generated.

Cleanup whisper a little

---

llms/mlx_lm/LORA.md
llms/mlx_lm/fuse.py
llms/mlx_lm/generate.py
llms/mlx_lm/lora.py
llms/mlx_lm/merge.py
llms/mlx_lm/server.py
llms/mlx_lm/tuner/trainer.py
llms/mlx_lm/tuner/utils.py
llms/mlx_lm/utils.py
llms/mlx_lm/version.py

- Save lora experiment config to json config
- Use safetensors for adapters
-  Read config as well as weights when loading lora model
Directory structure like:
```
adapters/
adapters.safetensors
adapter_config.json
```
Config looks like this:
```json
{
"adapter_path": "adapters",
"batch_size": 4,
"config": null,
"data": "../lora/data/",
"grad_checkpoint": false,
"iters": 11,
"learning_rate": 1e-05,
"lora_layers": 16,
"lora_parameters": {
"rank": 8,
"alpha": 16,
"dropout": 0.0,
"scale": 10.0
},
"max_seq_length": 2048,
"model": "Qwen/Qwen1.5-0.5B",
"resume_adapter_file": null,
"save_every": 10,
"seed": 0,
"steps_per_eval": 200,
"steps_per_report": 10,
"test": true,
"test_batches": 500,
"train": true,
"val_batches": 25
}
```

Save lora config

---

llms/mlx_lm/utils.py

Fix for empty initial string

---

stable_diffusion/stable_diffusion/__init__.py

Fixes #629. Missed that cause I was probably generating 1 image at a time on my laptop.

Fix CFG for SDXL

---

llms/mlx_lm/requirements.txt
llms/mlx_lm/sample_utils.py
llms/mlx_lm/utils.py
llms/mlx_lm/version.py

Companion to https://github.com/ml-explore/mlx/pulls
100+ tps out of the box 🚀
```
python -m mlx_lm.generate --model mlx-community/NeuralBeagle14-7B-4bit-mlx --prompt "Write a quick sort in python" --temp 0.0 --max-tokens 256
Fetching 6 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 68200.07it/s]
==========
Prompt: <|im_start|>user
Write a quick sort in python<|im_end|>
<|im_start|>assistant
Here's a quick implementation of the Quick Sort algorithm in Python:
```python
def partition(array, low, high):
"""
This function takes an array, a low index and a high index, and returns the index at which the array is partitioned.
"""
pivot = array[high]  # Choose the rightmost element as the pivot
i = low - 1  # …

Use async eval

---

llms/mlx_lm/tokenizer_utils.py

This basically allows streaming detokenization for the Gemma models.
If this continues (as in we find more decoders that need special cases) it might be worth checking if composable streaming detokenizers would be any slower. In that case we could just implement `ByteFallback`, `Strip`, `Replace` and a couple of others and compose them according to the `tokenizer.json` file.

Adapt SPM detokenizer to optionally not trim initial space

---

llms/mlx_lm/tuner/utils.py

Broke dequantization in #680 when started quantizing embeddings.

Fix dequantization

---

llms/gguf_llm/models.py
whisper/whisper/load_models.py

Fix quant in gguf

---

llms/mlx_lm/server.py
llms/mlx_lm/utils.py

It would be cool to support grammar's at some point like https://github.com/ggerganov/llama.cpp/pull/1773/files but for now this will suffice.

Add support for logit bias

---

llms/mlx_lm/server.py

This adds logging to the mlx server example for more visibility.
- Adds a `--log-level` parameter defaulting to `INFO`, with the options `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`.
- Switches the `print()` that happens on start to use `INFO`
- The `DEBUG` level now shows a pretty print of the incoming request body and response body.
- The `DEBUG` level now shows previews of generations as they complete in the console.

Add debug logging to MLX Server

---

lora/convert.py
lora/utils.py

One more quant fix

---

llms/mlx_lm/models/phi3.py
llms/mlx_lm/tuner/utils.py
llms/tests/test_models.py

This PR adds support for phi-3.

Add support for phi-3

---

llms/mlx_lm/lora.py
llms/mlx_lm/utils.py

- Don't overwrite config in test only mode, closes #710 
- Only load model specific params, closes https://github.com/ml-explore/mlx/issues/1027

Couple fixes for LoRA

---

llms/mlx_lm/models/openelm.py
llms/mlx_lm/tuner/utils.py

This PR adds support for openELM.

Add support for OpenELM

---

llms/mlx_lm/utils.py

- Add full link jump
- Add the address of the model uploader's Hugging Face homepage
- Add the -U parameter to always install the latest version of dependencies

Update model card describe

---

llms/mlx_lm/lora.py
llms/mlx_lm/models/qwen2_moe.py

Trivial fix for Qwen MOE to work in LoRA

Fix lora for qwen moe

---

llms/mlx_lm/generate.py
llms/mlx_lm/server.py

This PR is to address the MLX Cache concerns from https://github.com/ml-explore/mlx-examples/issues/724

Add MLX Cache Limit setting for mlx_lm.generate and mlx_lm.server CLI

---

llms/mlx_lm/utils.py
mnist/mnist.py

Use stable url for MNIST

---

llms/mlx_lm/models/llama.py
llms/tests/test_models.py

Not picked up in the tests.. :\

Fix llama cache check

---

llms/mlx_lm/tuner/trainer.py
llms/mlx_lm/tuner/utils.py

Fix lora for openelm

---

llms/mlx_lm/models/base.py
llms/tests/test_models.py

Support non incremental kv cache growth

---

whisper/setup.py

[mlx-whisper] Use namespace package to get rid of package install warning

---

llms/mlx_lm/lora.py
llms/mlx_lm/requirements.txt
llms/mlx_lm/tuner/utils.py
llms/mlx_lm/version.py

- Allow -1 to be all lora layers
- Fix reading from the config file in lora

version bump + some fixes

---

llms/mlx_lm/models/phi3.py

This PR adds support for Phi-3 Medium.

Add support for Phi-3 Medium

---

llms/mlx_lm/models/switch_layers.py
llms/mlx_lm/requirements.txt
llms/mlx_lm/utils.py

Rename block sparse to gather

---

llms/gguf_llm/requirements.txt

`huggingface_hub` was not included in `requirements.txt`.

fixed the requirements

---

llms/mlx_lm/models/mixtral.py
llms/mlx_lm/models/phixtral.py
llms/mlx_lm/models/qwen2_moe.py

Fix moe conversion

---

README.md
llms/mlx_lm/LORA.md
llms/mlx_lm/models/phi3small.py
llms/mlx_lm/requirements.txt
llms/mlx_lm/version.py

All pretty basic so far except the block sparse layers.
Also closes #805

Port of phi3small

---

whisper/mlx_whisper/audio.py

As title. Timings for 1 hour of audio:
Device | Time (milliseconds) |  Speedup over real time
---- | ---- | -----
CPU | 367 | 9,800
GPU | 20 | 180,000

GPU featurization for Whisper example

---

llms/mlx_lm/models/phi3.py
llms/mlx_lm/models/phi3small.py

Run the following command:
```shell
❯ mypy \
--explicit-package-bases \
--ignore-missing-imports \
. | grep models/phi
```
Before this change, it should complain the following:
```
mlx_lm/models/phi3small.py:22: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
mlx_lm/models/phi3small.py:29: error: Incompatible types in assignment (expression has type "Tuple[int]", variable has type "int")  [assignment]
mlx_lm/models/phi3small.py:74: error: Name "math" is not defined  [name-defined]
mlx_lm/models/phi3small.py:176: error: "Tuple[Any, Any]" has no attribute "offset"  [attr-defined]
mlx_lm/models/phi3small.py:177: error: "Tuple[Any, Any]" has no attribute "offset"  [attr-defined]
mlx_lm/models/phi3small.py:178: error: "Tuple[Any, …
```

make models/phi3.py and models/phi3small.py compatible with mypy

---

llms/mlx_lm/tuner/trainer.py
llms/mlx_lm/version.py

Add the eos token id to sequences during fine-tuning. Closes #811

Add eos token to lora fine-tunes

---

transformer_lm/datasets.py
transformer_lm/main.py

enwik8 is great for small runs if you're into small vocabularies!

transformer_lm: add --dataset enwik8

---

llms/mlx_lm/tokenizer_utils.py

Fix streaming SPM decoder for Yi

---

llms/mlx_lm/models/gpt_neox.py
llms/mlx_lm/tuner/utils.py
llms/tests/test_lora.py
llms/tests/test_models.py

Implement the GPT-NeoX model from https://huggingface.co/docs/transformers/en/model_doc/gpt_neox
On M2 Ultra (non quantized):
```
==========
Prompt: what
is the best way to do this?
A:
You can use the following code:
$('#my_div').html(function(i, html) {
return html.replace(/<br\s*\/
==========
Prompt: 0.943 tokens-per-sec
Generation: 15.146 tokens-per-sec
```
Closes https://github.com/ml-explore/mlx-examples/issues/847

Add GPT-NeoX model

---

llms/mlx_lm/lora.py

Enable Dora training with use_dora parameter

---

llms/mlx_lm/models/phi3.py

Add longrope to phi3.py

---

llms/mlx_lm/models/base.py
llms/mlx_lm/models/deepseek_v2.py

@awni I think this is ready for review and I tested on `deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct` and it seem work as expected.
Note:
- The yarn rope may be suboptimal, but I'm not very experienced with it so I pretty much copied exactly the PyTorch implementation.
- The MOE layer still doesn't return the exact output as the PyTorch implementation, but it seems like it can generate correct responses.
- `group_limited_greedy` is not implemented because I am unable to run it locally.

Add support for deepseek coder v2 lite

---

llms/mlx_lm/models/base.py
llms/mlx_lm/models/internlm2.py

This PR adds support for InternLM-2.5

Add support for InternLM-2.5

---

llms/mlx_lm/models/llama.py
llms/tests/test_models.py

Fixes based on fantastic work by @Blaizzy on https://github.com/ml-explore/mlx-examples/pull/906
Runs on my machine with llama-3.1-8b and llama-3.1-70b (still waiting for 405b download)

Add support for Llama-3.1

---

llms/mlx_lm/sample_utils.py
llms/mlx_lm/utils.py

Min P sampling implementation
- Added **min_p** and **min_tokens_to_keep** optional keyword arguments to _mlx_lm.utils.generate_step_
- Added **min_p_sampling** to _mlx_lm.sample_utils_

Min P implementation

---

llms/mlx_lm/tuner/utils.py

Enable fine tuning for deepseek

---

llms/mlx_lm/models/deepseek_v2.py
llms/mlx_lm/models/llama.py
llms/mlx_lm/models/phi3.py
llms/mlx_lm/models/su_rope.py
llms/mlx_lm/requirements.txt
llms/mlx_lm/version.py
stable_diffusion/stable_diffusion/unet.py

- Fixes the llama3.1 NTK RoPE implementation which was not correct
- Uses fast rope where possible
Will post some benchmarks shortly

Use fast rope

---

llms/mlx_lm/generate.py
llms/mlx_lm/version.py

Fix models without a chat template

---

llms/mlx_lm/utils.py

| Before | After |
|--------|--------|
| <img width="527" alt="image" src="https://github.com/user-attachments/assets/45660286-391f-42c1-b737-dd6fa26a9393"> | <img width="453" alt="image" src="https://github.com/user-attachments/assets/639d7f43-9e07-49c3-8ab7-921dad84a957"> |

Support HuggingFace model tree

---

llms/mlx_lm/LORA.md
llms/mlx_lm/utils.py

- I broke the uploading with some bad text formatting so this resolves that.
- Also made some clarifications in the LoRA docs about the dataset format.

Fix bug in upload + docs nit

---

llms/mlx_lm/LORA.md
llms/mlx_lm/tuner/datasets.py
llms/mlx_lm/tuner/trainer.py

The dataset supports the tools field, with a structure definition consistent with OpenAI [fine-tuning](https://platform.openai.com/docs/guides/fine-tuning/fine-tuning-examples) and HuggingFace [chat_template](https://huggingface.co/docs/transformers/main/en/chat_templating), as follows:
- datasets 
```josn
{
"messages": [
{ "role": "user", "content": "What is the weather in San Francisco?" },
{
"role": "assistant",
"tool_calls": [
{
"id": "call_id",
"type": "function",
"function": {
"name": "get_current_weather",
"arguments": "{\"location\": \"San Francisco, USA\", \"format\": \"celsius\"}"
}
}
]
}
],
"tools": [
{
"type": "function",
"function": {
"name": "get_current_weather",
"description": "Get the current weather",
"parameters": {
"type": "object",
"properties": {
"location": { …
```

LoRA: support tools(function calling) format datasets

---

llms/mlx_lm/server.py

Fix #784,  Related PR,  #995 .
Some examples of model requests:
- `meta-llama/Llama-3.2-1B-Instruct`
- `Qwen/Qwen2.5-0.5B-Instruct`
- `mistralai/Mistral-7B-Instruct-v0.3`
<details>
<summary>View the meta-llama/Llama-3.2-1B-Instruct cURL & response</summary>
- curl
```shell
curl http://localhost:8080/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
"model": "meta-llama/Llama-3.2-1B-Instruct",
"messages": [
{ "role": "user", "content": "What is the weather in San Francisco?" }
],
"tools": [
{
"type": "function",
"function": {
"name": "get_current_weather",
"description": "Get the current weather",
"parameters": {
"type": "object",
"properties": {
"location": {
"type": "string",
"description": "The city and country, eg. San Francisco, USA"
},
"format": { "type": "string", …
```

Server: support function calling

---

llms/mlx_lm/utils.py

Fix long prompt generations

---

llms/mlx_lm/utils.py

Closes #1025, see that for discussion / improvement.

Clear cache during prompt processing

---

.circleci/config.yml

bump mac tests to use py39

---

llms/mlx_lm/LORA.md

LoRA: update tools datasets docs

---

llms/mlx_lm/models/mamba.py
llms/mlx_lm/models/recurrent_gemma.py

Fix mamba models conversion

---

llms/mlx_lm/tokenizer_utils.py
llms/tests/test_tokenizers.py

Fix special tokens for deep seek

---

whisper/mlx_whisper/_version.py
whisper/mlx_whisper/decoding.py

Fix whisper edge case when decoding past limit

---

stable_diffusion/image2image.py

Allow to seed img2img explicitly

Add seed argument to stable diffusion image to image

---

stable_diffusion/image2image.py

Fix format

---

llms/README.md
llms/mlx_lm/README.md

Since awhile there has been a fully functional, no-code space to create MLX quantisations: https://huggingface.co/spaces/mlx-community/mlx-my-repo
This PR adds mentions of it in both the MLX LLM related READMEs.

Add mentions of MLX-my-repo.

---

llms/mlx_lm/tokenizer_utils.py
llms/mlx_lm/utils.py
llms/tests/test_utils_load_model.py

Support for multiple EOS tokens

---

llms/mlx_lm/sample_utils.py
llms/mlx_lm/server.py
llms/mlx_lm/utils.py

This was accidentally dropped during a previous refactor I did.

[mlx-lm] Use top p in server

---

llms/mlx_lm/_version.py
llms/mlx_lm/tokenizer_utils.py

Streaming BPE detokenization for character sequences which don't have spaces
Closes #1136

Bpe stream without space

---

llms/mlx_lm/evaluate.py

chore: update evaluate.py

---

llms/mlx_lm/generate.py
llms/mlx_lm/sample_utils.py
llms/tests/test_sample_utils.py

Fix no template prompt + top_k sampling

---

llms/mlx_lm/manage.py

Default is now N and size added to deletion confirmation screen.
Fix for #1177

Improvements to mlx_lm.manage

---

llms/mlx_lm/generate.py

Fix generation when `--extra-eos-token` is not set.

---

llms/mlx_lm/models/gpt_bigcode.py

Fix gpt bigcode

---

llms/mlx_lm/models/internlm3.py
llms/mlx_lm/tuner/utils.py
llms/tests/test_models.py

Convert to desired quant:
```
mlx_lm.convert --hf-path internlm/internlm3-8b-instruct -q --q-bits 4 --upload-repo mlx-community/internlm3-8b-instruct-4bit
```
Run:
```
mlx_lm.generate --model mlx-community/internlm3-8b-instruct-4bit --prompt "Write a story about Einstein"
==========
**The Timeless Encounter**
In the year 193193, a peculiar coincidence brought the renowned physicist, Albert Einstein, face to face with a young girl named Elara. Elara, a curious and imaginative youngster, had always been fascinated by the stories of the great minds of the past. One sunny afternoon, while exploring the vast expanse of the library, Elara stumbled upon a peculiar, almost ancient, pocket
==========
Prompt: 15 tokens, 92.460 tokens-per-sec
Generation: 100 tokens, 97.548 tokens-per-sec
Peak …
```

Add internlm3

---

llms/mlx_lm/sample_utils.py
llms/mlx_lm/utils.py
llms/tests/test_sample_utils.py

Batched min p and fix spec gen sampling

---

llms/mlx_lm/models/deepseek_v3.py

Arrived at clipped values by trial-end-error on a couple queries. Results seem to be identical with/without them (up to the point where overflow would happen).
Improves generation speed about 6% as compared to bf16.

Better overflow correction for DeepSeek v3

---

llms/mlx_lm/examples/pipeline_generate.py
llms/mlx_lm/models/deepseek_v2.py
llms/mlx_lm/models/deepseek_v3.py
llms/mlx_lm/utils.py

- Only download weights needed for the local shard for the pipeline parallel model
- Also added option to make dsv2 pipeline parallel for faster testing on smaller models

[mlx-lm] For pipeline parallel only download local shard

---

llms/mlx_lm/tuner/trainer.py

Fix no validation in lora

---

llms/mlx_lm/examples/pipeline_generate.py
llms/mlx_lm/models/deepseek_v2.py
llms/mlx_lm/models/deepseek_v3.py

Broke a couple things in https://github.com/ml-explore/mlx-examples/pull/1240, this fixes that.

Fix deepseek sharding

---

llms/mlx_lm/cache_prompt.py
llms/mlx_lm/generate.py
llms/mlx_lm/models/deepseek_v2.py

Fix prompt cache for models without chat template

---

llms/mlx_lm/generate.py
llms/mlx_lm/models/granite.py
llms/mlx_lm/tuner/utils.py

```
mlx_lm.generate --model ibm-granite/granite-3.2-8b-instruct-preview --prompt "Write a story about Einstein"
```
Closes #1264

Add IBM granite model

---

llms/mlx_lm/models/hunyuan.py

closes #1239 
Works with e.g.:
```
mlx_lm.generate --model mlx-community/Hunyuan-7B-Instruct-8bit --prompt "Write a story about Einstein" -m 256
```

Support hunyuan 7b

---

whisper/mlx_whisper/transcribe.py

Closes https://github.com/ml-explore/mlx-examples/issues/1256

Fix looping in whisper

---

llms/mlx_lm/evaluate.py

Fix generation evals

---

llms/mlx_lm/tuner/trainer.py

Accidentally starting the clock in the wrong place after validation would give artificially high times for the next report. Timings make sense now.

Fix lora timings after validation

---

llms/mlx_lm/tuner/utils.py

Hunyuan finetuning

---

llms/README.md

If you are like me and tried to pass temp as a argument just to realise that this gets passed via sampler I would like to save others some time.

Update README.md to include how to set temperature

---

transformer_lm/main.py

- Use a more standard windowing strategy so we don't blow up the dataset size by duplicating a bunch of tokens per example
- Remove numpy dependency
Closes #1286

[transformer_lm] Use more standard window strategy

---

llms/mlx_lm/lora.py
llms/mlx_lm/tuner/utils.py

Closes https://github.com/ml-explore/mlx-examples/issues/1289

Fix num layers in fine tune

---

llms/mlx_lm/_version.py
llms/mlx_lm/utils.py

Fixes ~3 bugs with spec-dec:
- Pass 2D logits to logits processor
- Fix previous token book-keeping
- Incorrect normalization of log probs for base model

Fix logits processor bugs with spec dec

---

llms/mlx_lm/convert.py
llms/mlx_lm/utils.py

Adding a couple of mixed 2/6, 3/6 quantization recipes for discussion, based on @barronalex's [gist](https://gist.github.com/barronalex/84addb8078be21969f1690c1454855f3). I think that mixed 4/6 is the same approach used now when q_bits is 4.
We could add some additional interesting recipes if there's interest.
I'll also run some tests on a couple of models.

Mixed quant recipes

---

llms/mlx_lm/manage.py

fix manage for new transformers

---

llms/mlx_lm/models/phi3.py
llms/mlx_lm/models/su_rope.py

```
mlx_lm.generate --model microsoft/Phi-4-mini-instruct --prompt "Write a story about Einstein" -m 2048 --extra-eos-token "<|end|>"
```

Fixes for phi4 mini

---

llms/mlx_lm/generate.py

usage:
```diff
python -m mlx_lm.generate \
--model mlx-community/DeepSeek-R1-Distill-Qwen-1.5B-4bit \
--prompt "hello" \
+       --prefill-response "<think>\n"
Fetching 6 files: 100%|████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 34521.02it/s]
==========
+Alright, the user said "hello." That's pretty straightforward. I should respond in a friendly and welcoming manner. Maybe something like, "Hello! How can I assist you today?" That should cover it. I don't want to overcomplicate things, just a simple hello and a request for their help.
</think>
Hello! How can I assist you today?
==========
Prompt: 6 tokens, 163.482 tokens-per-sec
Generation: 75 tokens, 247.778 tokens-per-sec
Peak memory: 1.014 GB
```

Generate: Support Prefill Response

---

llms/mlx_lm/lora.py

Allow mask prompt in config

---

llms/mlx_lm/models/plamo2.py

Thank you for fixing my messy code in #1283. However, it seems that some parts of the model code have changed, leading to slightly different behavior from the original. This PR aims at fixing it.

Fix plamo2 model to use rms_norm

---

.circleci/config.yml
README.md
llms/README.md
llms/mlx_lm/README.md

Update the main README to point to the new MLX LM and add some comments in the MLX LM readme about the move.

mlx-lm move notice

---

flux/README.md
flux/flux/layers.py
flux/flux/model.py
flux/generate_interactive.py
flux/txt2image.py

Add support for distributed inference for FLUX.

Distributed FLUX

---

.circleci/config.yml
llms/gguf_llm/generate.py
llms/gguf_llm/models.py
llms/llama/convert.py
llms/mixtral/mixtral.py
llms/speculative_decoding/decoder.py
llms/speculative_decoding/model.py
lora/lora.py
lora/models.py
lora/utils.py

Made llama and mistral files mypy compatible

---

lora/README.md

point to the correct repository
https://github.com/ml-explore/mlx-lm

Update lora README.md

---

whisper/benchmark.py
whisper/mlx_whisper/transcribe.py

whisper nits
